#!/bin/bash

# Set the working directory to the script's directory
script_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")"; pwd -P)
cd $script_dir

# Install ginkgo
go get github.com/onsi/ginkgo/ginkgo

# Install runc
go get -d github.com/opencontainers/runc
cd $GOPATH/src/github.com/opencontainers/runc
git checkout 882d8eaba6682179e397c78d5a40e45fa4d571ce
go install github.com/opencontainers/runc
cd $script_dir

# Generate busybox rootfs directory for runC tests
rootfs=runtime/runc/testbundle/rootfs
mkdir --parents $rootfs
sudo docker export $(sudo docker create busybox) | tar -C $rootfs -xvf - > /dev/null
