//go:build windows && (lcow || wcow)

// Code generated by MockGen. DO NOT EDIT.
// Source: internal/controller/vm/types.go
//
// Generated by this command:
//
//	mockgen -build_flags=-tags=windows,lcow -build_constraint=windows && (lcow || wcow) -source internal/controller/vm/types.go -package mocks -destination internal/controller/vm/mocks/mock_types.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	net "net"
	reflect "reflect"
	time "time"

	guid "github.com/Microsoft/go-winio/pkg/guid"
	cmd "github.com/Microsoft/hcsshim/internal/cmd"
	gcs "github.com/Microsoft/hcsshim/internal/gcs"
	schema2 "github.com/Microsoft/hcsshim/internal/hcs/schema2"
	guestresource "github.com/Microsoft/hcsshim/internal/protocol/guestresource"
	guestmanager "github.com/Microsoft/hcsshim/internal/vm/guestmanager"
	gomock "go.uber.org/mock/gomock"
)

// MockutilityVM is a mock of utilityVM interface.
type MockutilityVM struct {
	ctrl     *gomock.Controller
	recorder *MockutilityVMMockRecorder
	isgomock struct{}
}

// MockutilityVMMockRecorder is the mock recorder for MockutilityVM.
type MockutilityVMMockRecorder struct {
	mock *MockutilityVM
}

// NewMockutilityVM creates a new mock instance.
func NewMockutilityVM(ctrl *gomock.Controller) *MockutilityVM {
	mock := &MockutilityVM{ctrl: ctrl}
	mock.recorder = &MockutilityVMMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockutilityVM) EXPECT() *MockutilityVMMockRecorder {
	return m.recorder
}

// AcceptConnection mocks base method.
func (m *MockutilityVM) AcceptConnection(ctx context.Context, l net.Listener, closeConnection bool) (net.Conn, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AcceptConnection", ctx, l, closeConnection)
	ret0, _ := ret[0].(net.Conn)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AcceptConnection indicates an expected call of AcceptConnection.
func (mr *MockutilityVMMockRecorder) AcceptConnection(ctx, l, closeConnection any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AcceptConnection", reflect.TypeOf((*MockutilityVM)(nil).AcceptConnection), ctx, l, closeConnection)
}

// Close mocks base method.
func (m *MockutilityVM) Close(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockutilityVMMockRecorder) Close(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockutilityVM)(nil).Close), ctx)
}

// ExitError mocks base method.
func (m *MockutilityVM) ExitError() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExitError")
	ret0, _ := ret[0].(error)
	return ret0
}

// ExitError indicates an expected call of ExitError.
func (mr *MockutilityVMMockRecorder) ExitError() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExitError", reflect.TypeOf((*MockutilityVM)(nil).ExitError))
}

// ID mocks base method.
func (m *MockutilityVM) ID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ID")
	ret0, _ := ret[0].(string)
	return ret0
}

// ID indicates an expected call of ID.
func (mr *MockutilityVMMockRecorder) ID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ID", reflect.TypeOf((*MockutilityVM)(nil).ID))
}

// PropertiesV2 mocks base method.
func (m *MockutilityVM) PropertiesV2(ctx context.Context, types ...schema2.PropertyType) (*schema2.Properties, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range types {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "PropertiesV2", varargs...)
	ret0, _ := ret[0].(*schema2.Properties)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PropertiesV2 indicates an expected call of PropertiesV2.
func (mr *MockutilityVMMockRecorder) PropertiesV2(ctx any, types ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, types...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PropertiesV2", reflect.TypeOf((*MockutilityVM)(nil).PropertiesV2), varargs...)
}

// RuntimeID mocks base method.
func (m *MockutilityVM) RuntimeID() guid.GUID {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RuntimeID")
	ret0, _ := ret[0].(guid.GUID)
	return ret0
}

// RuntimeID indicates an expected call of RuntimeID.
func (mr *MockutilityVMMockRecorder) RuntimeID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RuntimeID", reflect.TypeOf((*MockutilityVM)(nil).RuntimeID))
}

// SetCPUGroup mocks base method.
func (m *MockutilityVM) SetCPUGroup(ctx context.Context, settings *schema2.CpuGroup) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetCPUGroup", ctx, settings)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetCPUGroup indicates an expected call of SetCPUGroup.
func (mr *MockutilityVMMockRecorder) SetCPUGroup(ctx, settings any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetCPUGroup", reflect.TypeOf((*MockutilityVM)(nil).SetCPUGroup), ctx, settings)
}

// Start mocks base method.
func (m *MockutilityVM) Start(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockutilityVMMockRecorder) Start(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockutilityVM)(nil).Start), ctx)
}

// StartedTime mocks base method.
func (m *MockutilityVM) StartedTime() time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartedTime")
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// StartedTime indicates an expected call of StartedTime.
func (mr *MockutilityVMMockRecorder) StartedTime() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartedTime", reflect.TypeOf((*MockutilityVM)(nil).StartedTime))
}

// StoppedTime mocks base method.
func (m *MockutilityVM) StoppedTime() time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoppedTime")
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// StoppedTime indicates an expected call of StoppedTime.
func (mr *MockutilityVMMockRecorder) StoppedTime() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoppedTime", reflect.TypeOf((*MockutilityVM)(nil).StoppedTime))
}

// Terminate mocks base method.
func (m *MockutilityVM) Terminate(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Terminate", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Terminate indicates an expected call of Terminate.
func (mr *MockutilityVMMockRecorder) Terminate(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Terminate", reflect.TypeOf((*MockutilityVM)(nil).Terminate), ctx)
}

// UpdateCPULimits mocks base method.
func (m *MockutilityVM) UpdateCPULimits(ctx context.Context, settings *schema2.ProcessorLimits) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCPULimits", ctx, settings)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCPULimits indicates an expected call of UpdateCPULimits.
func (mr *MockutilityVMMockRecorder) UpdateCPULimits(ctx, settings any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCPULimits", reflect.TypeOf((*MockutilityVM)(nil).UpdateCPULimits), ctx, settings)
}

// UpdateMemory mocks base method.
func (m *MockutilityVM) UpdateMemory(ctx context.Context, memory uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMemory", ctx, memory)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateMemory indicates an expected call of UpdateMemory.
func (mr *MockutilityVMMockRecorder) UpdateMemory(ctx, memory any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMemory", reflect.TypeOf((*MockutilityVM)(nil).UpdateMemory), ctx, memory)
}

// Wait mocks base method.
func (m *MockutilityVM) Wait(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Wait", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Wait indicates an expected call of Wait.
func (mr *MockutilityVMMockRecorder) Wait(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Wait", reflect.TypeOf((*MockutilityVM)(nil).Wait), ctx)
}

// MockguestManager is a mock of guestManager interface.
type MockguestManager struct {
	ctrl     *gomock.Controller
	recorder *MockguestManagerMockRecorder
	isgomock struct{}
}

// MockguestManagerMockRecorder is the mock recorder for MockguestManager.
type MockguestManagerMockRecorder struct {
	mock *MockguestManager
}

// NewMockguestManager creates a new mock instance.
func NewMockguestManager(ctrl *gomock.Controller) *MockguestManager {
	mock := &MockguestManager{ctrl: ctrl}
	mock.recorder = &MockguestManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockguestManager) EXPECT() *MockguestManagerMockRecorder {
	return m.recorder
}

// AddSecurityPolicy mocks base method.
func (m *MockguestManager) AddSecurityPolicy(ctx context.Context, opts guestresource.ConfidentialOptions) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddSecurityPolicy", ctx, opts)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddSecurityPolicy indicates an expected call of AddSecurityPolicy.
func (mr *MockguestManagerMockRecorder) AddSecurityPolicy(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddSecurityPolicy", reflect.TypeOf((*MockguestManager)(nil).AddSecurityPolicy), ctx, opts)
}

// Capabilities mocks base method.
func (m *MockguestManager) Capabilities() gcs.GuestDefinedCapabilities {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Capabilities")
	ret0, _ := ret[0].(gcs.GuestDefinedCapabilities)
	return ret0
}

// Capabilities indicates an expected call of Capabilities.
func (mr *MockguestManagerMockRecorder) Capabilities() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Capabilities", reflect.TypeOf((*MockguestManager)(nil).Capabilities))
}

// CloseConnection mocks base method.
func (m *MockguestManager) CloseConnection() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloseConnection")
	ret0, _ := ret[0].(error)
	return ret0
}

// CloseConnection indicates an expected call of CloseConnection.
func (mr *MockguestManagerMockRecorder) CloseConnection() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseConnection", reflect.TypeOf((*MockguestManager)(nil).CloseConnection))
}

// CreateConnection mocks base method.
func (m *MockguestManager) CreateConnection(ctx context.Context, opts ...guestmanager.ConfigOption) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateConnection", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateConnection indicates an expected call of CreateConnection.
func (mr *MockguestManagerMockRecorder) CreateConnection(ctx any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateConnection", reflect.TypeOf((*MockguestManager)(nil).CreateConnection), varargs...)
}

// DumpStacks mocks base method.
func (m *MockguestManager) DumpStacks(ctx context.Context) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DumpStacks", ctx)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DumpStacks indicates an expected call of DumpStacks.
func (mr *MockguestManagerMockRecorder) DumpStacks(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DumpStacks", reflect.TypeOf((*MockguestManager)(nil).DumpStacks), ctx)
}

// ExecIntoUVM mocks base method.
func (m *MockguestManager) ExecIntoUVM(ctx context.Context, request *cmd.CmdProcessRequest) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecIntoUVM", ctx, request)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExecIntoUVM indicates an expected call of ExecIntoUVM.
func (mr *MockguestManagerMockRecorder) ExecIntoUVM(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecIntoUVM", reflect.TypeOf((*MockguestManager)(nil).ExecIntoUVM), ctx, request)
}

// InjectPolicyFragment mocks base method.
func (m *MockguestManager) InjectPolicyFragment(ctx context.Context, fragment guestresource.SecurityPolicyFragment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InjectPolicyFragment", ctx, fragment)
	ret0, _ := ret[0].(error)
	return ret0
}

// InjectPolicyFragment indicates an expected call of InjectPolicyFragment.
func (mr *MockguestManagerMockRecorder) InjectPolicyFragment(ctx, fragment any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InjectPolicyFragment", reflect.TypeOf((*MockguestManager)(nil).InjectPolicyFragment), ctx, fragment)
}

// PrepareConnection mocks base method.
func (m *MockguestManager) PrepareConnection(GCSServiceID guid.GUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PrepareConnection", GCSServiceID)
	ret0, _ := ret[0].(error)
	return ret0
}

// PrepareConnection indicates an expected call of PrepareConnection.
func (mr *MockguestManagerMockRecorder) PrepareConnection(GCSServiceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PrepareConnection", reflect.TypeOf((*MockguestManager)(nil).PrepareConnection), GCSServiceID)
}
