// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: github.com/Microsoft/hcsshim/cmd/ncproxy/nodenetsvc/nodenetsvc.proto

package nodenetsvc

import (
	context "context"
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	io "io"
	math "math"
	reflect "reflect"
	strings "strings"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type RequestType int32

const (
	RequestType_Setup    RequestType = 0
	RequestType_Teardown RequestType = 1
)

var RequestType_name = map[int32]string{
	0: "Setup",
	1: "Teardown",
}

var RequestType_value = map[string]int32{
	"Setup":    0,
	"Teardown": 1,
}

func (x RequestType) String() string {
	return proto.EnumName(RequestType_name, int32(x))
}

func (RequestType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_3a65404bd96160d4, []int{0}
}

type ConfigureNetworkingRequest struct {
	ContainerID          string      `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	RequestType          RequestType `protobuf:"varint,2,opt,name=request_type,json=requestType,proto3,enum=azure.nodenetworkservice.RequestType" json:"request_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ConfigureNetworkingRequest) Reset()      { *m = ConfigureNetworkingRequest{} }
func (*ConfigureNetworkingRequest) ProtoMessage() {}
func (*ConfigureNetworkingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a65404bd96160d4, []int{0}
}
func (m *ConfigureNetworkingRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ConfigureNetworkingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ConfigureNetworkingRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ConfigureNetworkingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigureNetworkingRequest.Merge(m, src)
}
func (m *ConfigureNetworkingRequest) XXX_Size() int {
	return m.Size()
}
func (m *ConfigureNetworkingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigureNetworkingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigureNetworkingRequest proto.InternalMessageInfo

type ConfigureNetworkingResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfigureNetworkingResponse) Reset()      { *m = ConfigureNetworkingResponse{} }
func (*ConfigureNetworkingResponse) ProtoMessage() {}
func (*ConfigureNetworkingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a65404bd96160d4, []int{1}
}
func (m *ConfigureNetworkingResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ConfigureNetworkingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ConfigureNetworkingResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ConfigureNetworkingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigureNetworkingResponse.Merge(m, src)
}
func (m *ConfigureNetworkingResponse) XXX_Size() int {
	return m.Size()
}
func (m *ConfigureNetworkingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigureNetworkingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigureNetworkingResponse proto.InternalMessageInfo

type PingNodeNetworkServiceRequest struct {
	PingRequestMessage   string   `protobuf:"bytes,1,opt,name=ping_request_message,json=pingRequestMessage,proto3" json:"ping_request_message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingNodeNetworkServiceRequest) Reset()      { *m = PingNodeNetworkServiceRequest{} }
func (*PingNodeNetworkServiceRequest) ProtoMessage() {}
func (*PingNodeNetworkServiceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a65404bd96160d4, []int{2}
}
func (m *PingNodeNetworkServiceRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PingNodeNetworkServiceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PingNodeNetworkServiceRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PingNodeNetworkServiceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingNodeNetworkServiceRequest.Merge(m, src)
}
func (m *PingNodeNetworkServiceRequest) XXX_Size() int {
	return m.Size()
}
func (m *PingNodeNetworkServiceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PingNodeNetworkServiceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PingNodeNetworkServiceRequest proto.InternalMessageInfo

type PingNodeNetworkServiceResponse struct {
	PingResponseMessage  string   `protobuf:"bytes,1,opt,name=ping_response_message,json=pingResponseMessage,proto3" json:"ping_response_message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingNodeNetworkServiceResponse) Reset()      { *m = PingNodeNetworkServiceResponse{} }
func (*PingNodeNetworkServiceResponse) ProtoMessage() {}
func (*PingNodeNetworkServiceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a65404bd96160d4, []int{3}
}
func (m *PingNodeNetworkServiceResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PingNodeNetworkServiceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PingNodeNetworkServiceResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PingNodeNetworkServiceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingNodeNetworkServiceResponse.Merge(m, src)
}
func (m *PingNodeNetworkServiceResponse) XXX_Size() int {
	return m.Size()
}
func (m *PingNodeNetworkServiceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PingNodeNetworkServiceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PingNodeNetworkServiceResponse proto.InternalMessageInfo

type ConfigureContainerNetworkingRequest struct {
	RequestType          RequestType `protobuf:"varint,1,opt,name=request_type,json=requestType,proto3,enum=azure.nodenetworkservice.RequestType" json:"request_type,omitempty"`
	ContainerID          string      `protobuf:"bytes,2,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	NetworkNamespaceID   string      `protobuf:"bytes,3,opt,name=network_namespace_id,json=networkNamespaceId,proto3" json:"network_namespace_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ConfigureContainerNetworkingRequest) Reset()      { *m = ConfigureContainerNetworkingRequest{} }
func (*ConfigureContainerNetworkingRequest) ProtoMessage() {}
func (*ConfigureContainerNetworkingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a65404bd96160d4, []int{4}
}
func (m *ConfigureContainerNetworkingRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ConfigureContainerNetworkingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ConfigureContainerNetworkingRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ConfigureContainerNetworkingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigureContainerNetworkingRequest.Merge(m, src)
}
func (m *ConfigureContainerNetworkingRequest) XXX_Size() int {
	return m.Size()
}
func (m *ConfigureContainerNetworkingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigureContainerNetworkingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigureContainerNetworkingRequest proto.InternalMessageInfo

type ConfigureContainerNetworkingResponse struct {
	Interfaces           []*ContainerNetworkInterface `protobuf:"bytes,1,rep,name=interfaces,proto3" json:"interfaces,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *ConfigureContainerNetworkingResponse) Reset()      { *m = ConfigureContainerNetworkingResponse{} }
func (*ConfigureContainerNetworkingResponse) ProtoMessage() {}
func (*ConfigureContainerNetworkingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a65404bd96160d4, []int{5}
}
func (m *ConfigureContainerNetworkingResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ConfigureContainerNetworkingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ConfigureContainerNetworkingResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ConfigureContainerNetworkingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigureContainerNetworkingResponse.Merge(m, src)
}
func (m *ConfigureContainerNetworkingResponse) XXX_Size() int {
	return m.Size()
}
func (m *ConfigureContainerNetworkingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigureContainerNetworkingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigureContainerNetworkingResponse proto.InternalMessageInfo

type ContainerIPAddress struct {
	Version              string   `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Ip                   string   `protobuf:"bytes,3,opt,name=ip,proto3" json:"ip,omitempty"`
	PrefixLength         string   `protobuf:"bytes,4,opt,name=prefix_length,json=prefixLength,proto3" json:"prefix_length,omitempty"`
	DefaultGateway       string   `protobuf:"bytes,5,opt,name=default_gateway,json=defaultGateway,proto3" json:"default_gateway,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ContainerIPAddress) Reset()      { *m = ContainerIPAddress{} }
func (*ContainerIPAddress) ProtoMessage() {}
func (*ContainerIPAddress) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a65404bd96160d4, []int{6}
}
func (m *ContainerIPAddress) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ContainerIPAddress) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ContainerIPAddress.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ContainerIPAddress) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContainerIPAddress.Merge(m, src)
}
func (m *ContainerIPAddress) XXX_Size() int {
	return m.Size()
}
func (m *ContainerIPAddress) XXX_DiscardUnknown() {
	xxx_messageInfo_ContainerIPAddress.DiscardUnknown(m)
}

var xxx_messageInfo_ContainerIPAddress proto.InternalMessageInfo

type ContainerNetworkInterface struct {
	Name                 string                `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	MacAddress           string                `protobuf:"bytes,2,opt,name=mac_address,json=macAddress,proto3" json:"mac_address,omitempty"`
	NetworkNamespaceID   string                `protobuf:"bytes,3,opt,name=network_namespace_id,json=networkNamespaceId,proto3" json:"network_namespace_id,omitempty"`
	Ipaddresses          []*ContainerIPAddress `protobuf:"bytes,4,rep,name=ipaddresses,proto3" json:"ipaddresses,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ContainerNetworkInterface) Reset()      { *m = ContainerNetworkInterface{} }
func (*ContainerNetworkInterface) ProtoMessage() {}
func (*ContainerNetworkInterface) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a65404bd96160d4, []int{7}
}
func (m *ContainerNetworkInterface) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ContainerNetworkInterface) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ContainerNetworkInterface.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ContainerNetworkInterface) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContainerNetworkInterface.Merge(m, src)
}
func (m *ContainerNetworkInterface) XXX_Size() int {
	return m.Size()
}
func (m *ContainerNetworkInterface) XXX_DiscardUnknown() {
	xxx_messageInfo_ContainerNetworkInterface.DiscardUnknown(m)
}

var xxx_messageInfo_ContainerNetworkInterface proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("azure.nodenetworkservice.RequestType", RequestType_name, RequestType_value)
	proto.RegisterType((*ConfigureNetworkingRequest)(nil), "azure.nodenetworkservice.ConfigureNetworkingRequest")
	proto.RegisterType((*ConfigureNetworkingResponse)(nil), "azure.nodenetworkservice.ConfigureNetworkingResponse")
	proto.RegisterType((*PingNodeNetworkServiceRequest)(nil), "azure.nodenetworkservice.PingNodeNetworkServiceRequest")
	proto.RegisterType((*PingNodeNetworkServiceResponse)(nil), "azure.nodenetworkservice.PingNodeNetworkServiceResponse")
	proto.RegisterType((*ConfigureContainerNetworkingRequest)(nil), "azure.nodenetworkservice.ConfigureContainerNetworkingRequest")
	proto.RegisterType((*ConfigureContainerNetworkingResponse)(nil), "azure.nodenetworkservice.ConfigureContainerNetworkingResponse")
	proto.RegisterType((*ContainerIPAddress)(nil), "azure.nodenetworkservice.ContainerIPAddress")
	proto.RegisterType((*ContainerNetworkInterface)(nil), "azure.nodenetworkservice.ContainerNetworkInterface")
}

func init() {
	proto.RegisterFile("github.com/Microsoft/hcsshim/cmd/ncproxy/nodenetsvc/nodenetsvc.proto", fileDescriptor_3a65404bd96160d4)
}

var fileDescriptor_3a65404bd96160d4 = []byte{
	// 656 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0x5d, 0x4f, 0x13, 0x4d,
	0x14, 0x66, 0x0a, 0xbc, 0xef, 0xcb, 0x69, 0x5f, 0x20, 0x03, 0x92, 0xb5, 0x4a, 0x21, 0x0b, 0x2a,
	0x31, 0xa6, 0x35, 0x45, 0xa3, 0x37, 0x9a, 0x08, 0x24, 0xda, 0x44, 0x1a, 0x5c, 0xb8, 0xf2, 0x66,
	0xb3, 0xec, 0x9e, 0x6e, 0x27, 0xb2, 0x33, 0xe3, 0xcc, 0x16, 0xa8, 0xde, 0x18, 0x6f, 0xf5, 0x17,
	0x98, 0xf8, 0x7b, 0xe4, 0xd2, 0x4b, 0xaf, 0x88, 0xf4, 0xd2, 0xc4, 0xff, 0x60, 0xd8, 0x8f, 0xb6,
	0x29, 0x6c, 0x03, 0xc4, 0xbb, 0x99, 0xe7, 0xcc, 0x79, 0xe6, 0x79, 0xce, 0x99, 0x0f, 0xd8, 0xf0,
	0x59, 0xd8, 0x6c, 0xed, 0x96, 0x5d, 0x11, 0x54, 0x36, 0x99, 0xab, 0x84, 0x16, 0x8d, 0xb0, 0xd2,
	0x74, 0xb5, 0x6e, 0xb2, 0xa0, 0xe2, 0x06, 0x5e, 0x85, 0xbb, 0x52, 0x89, 0xc3, 0x76, 0x85, 0x0b,
	0x0f, 0x39, 0x86, 0x7a, 0xdf, 0xed, 0x1b, 0x96, 0xa5, 0x12, 0xa1, 0xa0, 0x86, 0xf3, 0xae, 0xa5,
	0xb0, 0x9c, 0xe0, 0x07, 0x42, 0xbd, 0xd1, 0xa8, 0xf6, 0x99, 0x8b, 0xe6, 0x17, 0x02, 0xc5, 0x75,
	0xc1, 0x1b, 0xcc, 0x6f, 0x29, 0xac, 0xc7, 0x31, 0xc6, 0x7d, 0x0b, 0xdf, 0xb6, 0x50, 0x87, 0xb4,
	0x0a, 0x05, 0x57, 0xf0, 0xd0, 0x61, 0x1c, 0x95, 0xcd, 0x3c, 0x83, 0x2c, 0x92, 0x95, 0x89, 0xb5,
	0xa9, 0xce, 0xf1, 0x42, 0x7e, 0x3d, 0xc5, 0x6b, 0x1b, 0x56, 0xbe, 0xbb, 0xa8, 0xe6, 0xd1, 0x17,
	0x50, 0x50, 0x71, 0xba, 0x1d, 0xb6, 0x25, 0x1a, 0xb9, 0x45, 0xb2, 0x32, 0x59, 0xbd, 0x55, 0xce,
	0xd2, 0x50, 0x4e, 0x36, 0xdb, 0x69, 0x4b, 0xb4, 0xf2, 0xaa, 0x37, 0x31, 0xe7, 0xe1, 0xc6, 0xb9,
	0xda, 0xb4, 0x14, 0x5c, 0xa3, 0xf9, 0x0a, 0xe6, 0xb7, 0x18, 0xf7, 0xeb, 0xc2, 0x4b, 0xa3, 0xdb,
	0x31, 0x63, 0xaa, 0xfe, 0x3e, 0xcc, 0x4a, 0xc6, 0x7d, 0x3b, 0x95, 0x13, 0xa0, 0xd6, 0x8e, 0x8f,
	0xb1, 0x0b, 0x8b, 0xca, 0x9e, 0xd1, 0xcd, 0x38, 0x62, 0xee, 0x40, 0x29, 0x8b, 0x32, 0xde, 0x94,
	0x56, 0xe1, 0x5a, 0xc2, 0x19, 0x03, 0x03, 0xa4, 0x33, 0xb2, 0x4f, 0x61, 0xca, 0xfa, 0x9b, 0xc0,
	0x52, 0xd7, 0x48, 0xb7, 0x6e, 0x67, 0xab, 0x3d, 0x58, 0x39, 0x72, 0xd5, 0xca, 0x9d, 0xe9, 0x5b,
	0xee, 0x42, 0x7d, 0x9b, 0x4d, 0xe8, 0x6d, 0xee, 0x04, 0xa8, 0xa5, 0xe3, 0xe2, 0x69, 0xee, 0x68,
	0x94, 0x3b, 0xd7, 0x39, 0x5e, 0xa0, 0x89, 0xe4, 0x7a, 0x1a, 0xae, 0x6d, 0x58, 0x94, 0x0f, 0x62,
	0x9e, 0xf9, 0x1e, 0x96, 0x87, 0xdb, 0x4d, 0x6a, 0xb9, 0x0d, 0xc0, 0x78, 0x88, 0xaa, 0xe1, 0xb8,
	0xa8, 0x0d, 0xb2, 0x38, 0xba, 0x92, 0xaf, 0xae, 0x66, 0xbb, 0x1d, 0xa4, 0xaa, 0xa5, 0xb9, 0x56,
	0x1f, 0x8d, 0xf9, 0x99, 0x00, 0xed, 0x79, 0xdc, 0x7a, 0xe6, 0x79, 0x0a, 0xb5, 0xa6, 0x06, 0xfc,
	0xbb, 0x8f, 0x4a, 0x33, 0xc1, 0x93, 0x4e, 0xa5, 0x53, 0x3a, 0x09, 0x39, 0x26, 0x63, 0x97, 0x56,
	0x8e, 0x49, 0xba, 0x04, 0xff, 0x4b, 0x85, 0x0d, 0x76, 0x68, 0xef, 0x21, 0xf7, 0xc3, 0xa6, 0x31,
	0x16, 0x85, 0x0a, 0x31, 0xf8, 0x32, 0xc2, 0xe8, 0x1d, 0x98, 0xf2, 0xb0, 0xe1, 0xb4, 0xf6, 0x42,
	0xdb, 0x77, 0x42, 0x3c, 0x70, 0xda, 0xc6, 0x78, 0xb4, 0x6c, 0x32, 0x81, 0x9f, 0xc7, 0xa8, 0xf9,
	0x8b, 0xc0, 0xf5, 0x4c, 0xe1, 0x94, 0xc2, 0xd8, 0x69, 0xad, 0x13, 0x49, 0xd1, 0x98, 0x2e, 0x40,
	0x3e, 0x70, 0x5c, 0xdb, 0x89, 0x85, 0xc7, 0xad, 0xb3, 0x20, 0x70, 0xdc, 0xd4, 0xca, 0x5f, 0x6b,
	0x14, 0xad, 0x43, 0x9e, 0xc9, 0x64, 0x23, 0xd4, 0xc6, 0x58, 0xd4, 0x81, 0x7b, 0x17, 0xe8, 0x40,
	0xb7, 0xae, 0x56, 0x3f, 0xc1, 0xdd, 0xdb, 0x90, 0xef, 0x3b, 0x92, 0x74, 0x02, 0xc6, 0xb7, 0x31,
	0x6c, 0xc9, 0xe9, 0x11, 0x5a, 0x80, 0xff, 0x76, 0xd0, 0x51, 0x9e, 0x38, 0xe0, 0xd3, 0xa4, 0xfa,
	0x6d, 0x14, 0xe8, 0xd9, 0x3b, 0x46, 0x3f, 0x12, 0x98, 0x39, 0xe7, 0xc2, 0xd3, 0x07, 0x43, 0x15,
	0x65, 0xbc, 0x5d, 0xc5, 0x87, 0x97, 0xcc, 0x4a, 0x0e, 0xe5, 0x57, 0x02, 0x37, 0x87, 0x9d, 0x5e,
	0xfa, 0xe4, 0x02, 0xbc, 0xd9, 0x97, 0xbc, 0xf8, 0xf4, 0xaa, 0xe9, 0x89, 0xbe, 0x4f, 0x04, 0xe6,
	0xce, 0x7f, 0xa3, 0xe8, 0xa3, 0x6c, 0xea, 0xa1, 0x0f, 0x65, 0xf1, 0xf1, 0xe5, 0x13, 0x63, 0x35,
	0x6b, 0xcb, 0x47, 0x27, 0xa5, 0x91, 0x1f, 0x27, 0xa5, 0x91, 0x0f, 0x9d, 0x12, 0x39, 0xea, 0x94,
	0xc8, 0xf7, 0x4e, 0x89, 0xfc, 0xec, 0x94, 0xc8, 0x6b, 0xe8, 0xfd, 0x42, 0xbb, 0xff, 0x44, 0xdf,
	0xd0, 0xea, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x3d, 0x38, 0x49, 0xb3, 0xce, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// NodeNetworkServiceClient is the client API for NodeNetworkService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type NodeNetworkServiceClient interface {
	ConfigureNetworking(ctx context.Context, in *ConfigureNetworkingRequest, opts ...grpc.CallOption) (*ConfigureNetworkingResponse, error)
	ConfigureContainerNetworking(ctx context.Context, in *ConfigureContainerNetworkingRequest, opts ...grpc.CallOption) (*ConfigureContainerNetworkingResponse, error)
	PingNodeNetworkService(ctx context.Context, in *PingNodeNetworkServiceRequest, opts ...grpc.CallOption) (*PingNodeNetworkServiceResponse, error)
}

type nodeNetworkServiceClient struct {
	cc *grpc.ClientConn
}

func NewNodeNetworkServiceClient(cc *grpc.ClientConn) NodeNetworkServiceClient {
	return &nodeNetworkServiceClient{cc}
}

func (c *nodeNetworkServiceClient) ConfigureNetworking(ctx context.Context, in *ConfigureNetworkingRequest, opts ...grpc.CallOption) (*ConfigureNetworkingResponse, error) {
	out := new(ConfigureNetworkingResponse)
	err := c.cc.Invoke(ctx, "/azure.nodenetworkservice.NodeNetworkService/ConfigureNetworking", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeNetworkServiceClient) ConfigureContainerNetworking(ctx context.Context, in *ConfigureContainerNetworkingRequest, opts ...grpc.CallOption) (*ConfigureContainerNetworkingResponse, error) {
	out := new(ConfigureContainerNetworkingResponse)
	err := c.cc.Invoke(ctx, "/azure.nodenetworkservice.NodeNetworkService/ConfigureContainerNetworking", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeNetworkServiceClient) PingNodeNetworkService(ctx context.Context, in *PingNodeNetworkServiceRequest, opts ...grpc.CallOption) (*PingNodeNetworkServiceResponse, error) {
	out := new(PingNodeNetworkServiceResponse)
	err := c.cc.Invoke(ctx, "/azure.nodenetworkservice.NodeNetworkService/PingNodeNetworkService", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NodeNetworkServiceServer is the server API for NodeNetworkService service.
type NodeNetworkServiceServer interface {
	ConfigureNetworking(context.Context, *ConfigureNetworkingRequest) (*ConfigureNetworkingResponse, error)
	ConfigureContainerNetworking(context.Context, *ConfigureContainerNetworkingRequest) (*ConfigureContainerNetworkingResponse, error)
	PingNodeNetworkService(context.Context, *PingNodeNetworkServiceRequest) (*PingNodeNetworkServiceResponse, error)
}

func RegisterNodeNetworkServiceServer(s *grpc.Server, srv NodeNetworkServiceServer) {
	s.RegisterService(&_NodeNetworkService_serviceDesc, srv)
}

func _NodeNetworkService_ConfigureNetworking_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigureNetworkingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeNetworkServiceServer).ConfigureNetworking(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/azure.nodenetworkservice.NodeNetworkService/ConfigureNetworking",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeNetworkServiceServer).ConfigureNetworking(ctx, req.(*ConfigureNetworkingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeNetworkService_ConfigureContainerNetworking_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigureContainerNetworkingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeNetworkServiceServer).ConfigureContainerNetworking(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/azure.nodenetworkservice.NodeNetworkService/ConfigureContainerNetworking",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeNetworkServiceServer).ConfigureContainerNetworking(ctx, req.(*ConfigureContainerNetworkingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeNetworkService_PingNodeNetworkService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingNodeNetworkServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeNetworkServiceServer).PingNodeNetworkService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/azure.nodenetworkservice.NodeNetworkService/PingNodeNetworkService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeNetworkServiceServer).PingNodeNetworkService(ctx, req.(*PingNodeNetworkServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _NodeNetworkService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "azure.nodenetworkservice.NodeNetworkService",
	HandlerType: (*NodeNetworkServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ConfigureNetworking",
			Handler:    _NodeNetworkService_ConfigureNetworking_Handler,
		},
		{
			MethodName: "ConfigureContainerNetworking",
			Handler:    _NodeNetworkService_ConfigureContainerNetworking_Handler,
		},
		{
			MethodName: "PingNodeNetworkService",
			Handler:    _NodeNetworkService_PingNodeNetworkService_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "github.com/Microsoft/hcsshim/cmd/ncproxy/nodenetsvc/nodenetsvc.proto",
}

func (m *ConfigureNetworkingRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ConfigureNetworkingRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.ContainerID) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintNodenetsvc(dAtA, i, uint64(len(m.ContainerID)))
		i += copy(dAtA[i:], m.ContainerID)
	}
	if m.RequestType != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintNodenetsvc(dAtA, i, uint64(m.RequestType))
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *ConfigureNetworkingResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ConfigureNetworkingResponse) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *PingNodeNetworkServiceRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PingNodeNetworkServiceRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.PingRequestMessage) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintNodenetsvc(dAtA, i, uint64(len(m.PingRequestMessage)))
		i += copy(dAtA[i:], m.PingRequestMessage)
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *PingNodeNetworkServiceResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PingNodeNetworkServiceResponse) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.PingResponseMessage) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintNodenetsvc(dAtA, i, uint64(len(m.PingResponseMessage)))
		i += copy(dAtA[i:], m.PingResponseMessage)
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *ConfigureContainerNetworkingRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ConfigureContainerNetworkingRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.RequestType != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintNodenetsvc(dAtA, i, uint64(m.RequestType))
	}
	if len(m.ContainerID) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintNodenetsvc(dAtA, i, uint64(len(m.ContainerID)))
		i += copy(dAtA[i:], m.ContainerID)
	}
	if len(m.NetworkNamespaceID) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintNodenetsvc(dAtA, i, uint64(len(m.NetworkNamespaceID)))
		i += copy(dAtA[i:], m.NetworkNamespaceID)
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *ConfigureContainerNetworkingResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ConfigureContainerNetworkingResponse) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Interfaces) > 0 {
		for _, msg := range m.Interfaces {
			dAtA[i] = 0xa
			i++
			i = encodeVarintNodenetsvc(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *ContainerIPAddress) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ContainerIPAddress) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Version) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintNodenetsvc(dAtA, i, uint64(len(m.Version)))
		i += copy(dAtA[i:], m.Version)
	}
	if len(m.Ip) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintNodenetsvc(dAtA, i, uint64(len(m.Ip)))
		i += copy(dAtA[i:], m.Ip)
	}
	if len(m.PrefixLength) > 0 {
		dAtA[i] = 0x22
		i++
		i = encodeVarintNodenetsvc(dAtA, i, uint64(len(m.PrefixLength)))
		i += copy(dAtA[i:], m.PrefixLength)
	}
	if len(m.DefaultGateway) > 0 {
		dAtA[i] = 0x2a
		i++
		i = encodeVarintNodenetsvc(dAtA, i, uint64(len(m.DefaultGateway)))
		i += copy(dAtA[i:], m.DefaultGateway)
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *ContainerNetworkInterface) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ContainerNetworkInterface) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Name) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintNodenetsvc(dAtA, i, uint64(len(m.Name)))
		i += copy(dAtA[i:], m.Name)
	}
	if len(m.MacAddress) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintNodenetsvc(dAtA, i, uint64(len(m.MacAddress)))
		i += copy(dAtA[i:], m.MacAddress)
	}
	if len(m.NetworkNamespaceID) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintNodenetsvc(dAtA, i, uint64(len(m.NetworkNamespaceID)))
		i += copy(dAtA[i:], m.NetworkNamespaceID)
	}
	if len(m.Ipaddresses) > 0 {
		for _, msg := range m.Ipaddresses {
			dAtA[i] = 0x22
			i++
			i = encodeVarintNodenetsvc(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func encodeVarintNodenetsvc(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *ConfigureNetworkingRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ContainerID)
	if l > 0 {
		n += 1 + l + sovNodenetsvc(uint64(l))
	}
	if m.RequestType != 0 {
		n += 1 + sovNodenetsvc(uint64(m.RequestType))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *ConfigureNetworkingResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *PingNodeNetworkServiceRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.PingRequestMessage)
	if l > 0 {
		n += 1 + l + sovNodenetsvc(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *PingNodeNetworkServiceResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.PingResponseMessage)
	if l > 0 {
		n += 1 + l + sovNodenetsvc(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *ConfigureContainerNetworkingRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.RequestType != 0 {
		n += 1 + sovNodenetsvc(uint64(m.RequestType))
	}
	l = len(m.ContainerID)
	if l > 0 {
		n += 1 + l + sovNodenetsvc(uint64(l))
	}
	l = len(m.NetworkNamespaceID)
	if l > 0 {
		n += 1 + l + sovNodenetsvc(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *ConfigureContainerNetworkingResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Interfaces) > 0 {
		for _, e := range m.Interfaces {
			l = e.Size()
			n += 1 + l + sovNodenetsvc(uint64(l))
		}
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *ContainerIPAddress) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Version)
	if l > 0 {
		n += 1 + l + sovNodenetsvc(uint64(l))
	}
	l = len(m.Ip)
	if l > 0 {
		n += 1 + l + sovNodenetsvc(uint64(l))
	}
	l = len(m.PrefixLength)
	if l > 0 {
		n += 1 + l + sovNodenetsvc(uint64(l))
	}
	l = len(m.DefaultGateway)
	if l > 0 {
		n += 1 + l + sovNodenetsvc(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *ContainerNetworkInterface) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovNodenetsvc(uint64(l))
	}
	l = len(m.MacAddress)
	if l > 0 {
		n += 1 + l + sovNodenetsvc(uint64(l))
	}
	l = len(m.NetworkNamespaceID)
	if l > 0 {
		n += 1 + l + sovNodenetsvc(uint64(l))
	}
	if len(m.Ipaddresses) > 0 {
		for _, e := range m.Ipaddresses {
			l = e.Size()
			n += 1 + l + sovNodenetsvc(uint64(l))
		}
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovNodenetsvc(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozNodenetsvc(x uint64) (n int) {
	return sovNodenetsvc(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *ConfigureNetworkingRequest) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&ConfigureNetworkingRequest{`,
		`ContainerID:` + fmt.Sprintf("%v", this.ContainerID) + `,`,
		`RequestType:` + fmt.Sprintf("%v", this.RequestType) + `,`,
		`XXX_unrecognized:` + fmt.Sprintf("%v", this.XXX_unrecognized) + `,`,
		`}`,
	}, "")
	return s
}
func (this *ConfigureNetworkingResponse) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&ConfigureNetworkingResponse{`,
		`XXX_unrecognized:` + fmt.Sprintf("%v", this.XXX_unrecognized) + `,`,
		`}`,
	}, "")
	return s
}
func (this *PingNodeNetworkServiceRequest) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&PingNodeNetworkServiceRequest{`,
		`PingRequestMessage:` + fmt.Sprintf("%v", this.PingRequestMessage) + `,`,
		`XXX_unrecognized:` + fmt.Sprintf("%v", this.XXX_unrecognized) + `,`,
		`}`,
	}, "")
	return s
}
func (this *PingNodeNetworkServiceResponse) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&PingNodeNetworkServiceResponse{`,
		`PingResponseMessage:` + fmt.Sprintf("%v", this.PingResponseMessage) + `,`,
		`XXX_unrecognized:` + fmt.Sprintf("%v", this.XXX_unrecognized) + `,`,
		`}`,
	}, "")
	return s
}
func (this *ConfigureContainerNetworkingRequest) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&ConfigureContainerNetworkingRequest{`,
		`RequestType:` + fmt.Sprintf("%v", this.RequestType) + `,`,
		`ContainerID:` + fmt.Sprintf("%v", this.ContainerID) + `,`,
		`NetworkNamespaceID:` + fmt.Sprintf("%v", this.NetworkNamespaceID) + `,`,
		`XXX_unrecognized:` + fmt.Sprintf("%v", this.XXX_unrecognized) + `,`,
		`}`,
	}, "")
	return s
}
func (this *ConfigureContainerNetworkingResponse) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&ConfigureContainerNetworkingResponse{`,
		`Interfaces:` + strings.Replace(fmt.Sprintf("%v", this.Interfaces), "ContainerNetworkInterface", "ContainerNetworkInterface", 1) + `,`,
		`XXX_unrecognized:` + fmt.Sprintf("%v", this.XXX_unrecognized) + `,`,
		`}`,
	}, "")
	return s
}
func (this *ContainerIPAddress) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&ContainerIPAddress{`,
		`Version:` + fmt.Sprintf("%v", this.Version) + `,`,
		`Ip:` + fmt.Sprintf("%v", this.Ip) + `,`,
		`PrefixLength:` + fmt.Sprintf("%v", this.PrefixLength) + `,`,
		`DefaultGateway:` + fmt.Sprintf("%v", this.DefaultGateway) + `,`,
		`XXX_unrecognized:` + fmt.Sprintf("%v", this.XXX_unrecognized) + `,`,
		`}`,
	}, "")
	return s
}
func (this *ContainerNetworkInterface) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&ContainerNetworkInterface{`,
		`Name:` + fmt.Sprintf("%v", this.Name) + `,`,
		`MacAddress:` + fmt.Sprintf("%v", this.MacAddress) + `,`,
		`NetworkNamespaceID:` + fmt.Sprintf("%v", this.NetworkNamespaceID) + `,`,
		`Ipaddresses:` + strings.Replace(fmt.Sprintf("%v", this.Ipaddresses), "ContainerIPAddress", "ContainerIPAddress", 1) + `,`,
		`XXX_unrecognized:` + fmt.Sprintf("%v", this.XXX_unrecognized) + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringNodenetsvc(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *ConfigureNetworkingRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowNodenetsvc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ConfigureNetworkingRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ConfigureNetworkingRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContainerID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNodenetsvc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthNodenetsvc
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthNodenetsvc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ContainerID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RequestType", wireType)
			}
			m.RequestType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNodenetsvc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RequestType |= RequestType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipNodenetsvc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthNodenetsvc
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthNodenetsvc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ConfigureNetworkingResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowNodenetsvc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ConfigureNetworkingResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ConfigureNetworkingResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipNodenetsvc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthNodenetsvc
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthNodenetsvc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PingNodeNetworkServiceRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowNodenetsvc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PingNodeNetworkServiceRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PingNodeNetworkServiceRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PingRequestMessage", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNodenetsvc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthNodenetsvc
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthNodenetsvc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PingRequestMessage = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipNodenetsvc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthNodenetsvc
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthNodenetsvc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PingNodeNetworkServiceResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowNodenetsvc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PingNodeNetworkServiceResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PingNodeNetworkServiceResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PingResponseMessage", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNodenetsvc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthNodenetsvc
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthNodenetsvc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PingResponseMessage = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipNodenetsvc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthNodenetsvc
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthNodenetsvc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ConfigureContainerNetworkingRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowNodenetsvc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ConfigureContainerNetworkingRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ConfigureContainerNetworkingRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RequestType", wireType)
			}
			m.RequestType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNodenetsvc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RequestType |= RequestType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContainerID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNodenetsvc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthNodenetsvc
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthNodenetsvc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ContainerID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NetworkNamespaceID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNodenetsvc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthNodenetsvc
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthNodenetsvc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NetworkNamespaceID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipNodenetsvc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthNodenetsvc
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthNodenetsvc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ConfigureContainerNetworkingResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowNodenetsvc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ConfigureContainerNetworkingResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ConfigureContainerNetworkingResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Interfaces", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNodenetsvc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthNodenetsvc
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthNodenetsvc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Interfaces = append(m.Interfaces, &ContainerNetworkInterface{})
			if err := m.Interfaces[len(m.Interfaces)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipNodenetsvc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthNodenetsvc
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthNodenetsvc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ContainerIPAddress) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowNodenetsvc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ContainerIPAddress: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ContainerIPAddress: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Version", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNodenetsvc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthNodenetsvc
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthNodenetsvc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Version = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Ip", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNodenetsvc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthNodenetsvc
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthNodenetsvc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Ip = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PrefixLength", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNodenetsvc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthNodenetsvc
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthNodenetsvc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PrefixLength = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DefaultGateway", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNodenetsvc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthNodenetsvc
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthNodenetsvc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DefaultGateway = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipNodenetsvc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthNodenetsvc
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthNodenetsvc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ContainerNetworkInterface) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowNodenetsvc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ContainerNetworkInterface: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ContainerNetworkInterface: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNodenetsvc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthNodenetsvc
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthNodenetsvc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MacAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNodenetsvc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthNodenetsvc
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthNodenetsvc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MacAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NetworkNamespaceID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNodenetsvc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthNodenetsvc
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthNodenetsvc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NetworkNamespaceID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Ipaddresses", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNodenetsvc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthNodenetsvc
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthNodenetsvc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Ipaddresses = append(m.Ipaddresses, &ContainerIPAddress{})
			if err := m.Ipaddresses[len(m.Ipaddresses)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipNodenetsvc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthNodenetsvc
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthNodenetsvc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipNodenetsvc(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowNodenetsvc
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowNodenetsvc
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowNodenetsvc
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthNodenetsvc
			}
			iNdEx += length
			if iNdEx < 0 {
				return 0, ErrInvalidLengthNodenetsvc
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowNodenetsvc
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipNodenetsvc(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
				if iNdEx < 0 {
					return 0, ErrInvalidLengthNodenetsvc
				}
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthNodenetsvc = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowNodenetsvc   = fmt.Errorf("proto: integer overflow")
)
