// Autogenerated code; DO NOT EDIT.

// Schema retrieved from branch 'fe_release' and build '20348.1.210507-1500'.

/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema

// IntegrationComponentOperationalState : Operational status for integration component
type IntegrationComponentOperationalState string

// List of IntegrationComponentOperationalState
const (
	IntegrationComponentOperationalState_UNKNOWN               IntegrationComponentOperationalState = "Unknown"
	IntegrationComponentOperationalState_DEGRADED              IntegrationComponentOperationalState = "Degraded"
	IntegrationComponentOperationalState_DORMANT               IntegrationComponentOperationalState = "Dormant"
	IntegrationComponentOperationalState_ERROR_                IntegrationComponentOperationalState = "Error"
	IntegrationComponentOperationalState_LOST_COMMUNICATION    IntegrationComponentOperationalState = "LostCommunication"
	IntegrationComponentOperationalState_NON_RECOVERABLE_ERROR IntegrationComponentOperationalState = "NonRecoverableError"
	IntegrationComponentOperationalState_NO_CONTACT            IntegrationComponentOperationalState = "NoContact"
	IntegrationComponentOperationalState_OK                    IntegrationComponentOperationalState = "Ok"
)
