// Autogenerated code; DO NOT EDIT.

// Schema retrieved from branch 'fe_release' and build '20348.1.210507-1500'.

/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema

// IntegrationComponentOperatingStateReason : Possible reason for integration component's state
type IntegrationComponentOperatingStateReason string

// List of IntegrationComponentOperatingStateReason
const (
	IntegrationComponentOperatingStateReason_UNKNOWN                 IntegrationComponentOperatingStateReason = "Unknown"
	IntegrationComponentOperatingStateReason_APPS_IN_CRITICAL_STATE  IntegrationComponentOperatingStateReason = "AppsInCriticalState"
	IntegrationComponentOperatingStateReason_COMMUNICATION_TIMED_OUT IntegrationComponentOperatingStateReason = "CommunicationTimedOut"
	IntegrationComponentOperatingStateReason_FAILED_COMMUNICATION    IntegrationComponentOperatingStateReason = "FailedCommunication"
	IntegrationComponentOperatingStateReason_HEALTHY_APPS            IntegrationComponentOperatingStateReason = "HealthyApps"
	IntegrationComponentOperatingStateReason_PROTOCOL_MISMATCH       IntegrationComponentOperatingStateReason = "ProtocolMismatch"
)
