// Autogenerated code; DO NOT EDIT.

// Schema retrieved from branch 'fe_release' and build '20348.1.210507-1500'.

/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema

type LinuxBlockIO struct {
	Weight                  uint16                `json:"weight,omitempty"`
	LeafWeight              uint16                `json:"leafWeight,omitempty"`
	WeightDevice            []LinuxWeightDevice   `json:"weightDevice,omitempty"`
	ThrottleReadBpsDevice   []LinuxThrottleDevice `json:"throttleReadBpsDevice,omitempty"`
	ThrottleWriteBpsDevice  []LinuxThrottleDevice `json:"throttleWriteBpsDevice,omitempty"`
	ThrottleReadIOPSDevice  []LinuxThrottleDevice `json:"throttleReadIOPSDevice,omitempty"`
	ThrottleWriteIOPSDevice []LinuxThrottleDevice `json:"throttleWriteIOPSDevice,omitempty"`
}
