// Autogenerated code; DO NOT EDIT.

// Schema retrieved from branch 'main' and build '27598.1000.2404101356'.

/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swaggerapi/swaggercodegen)
 *
 * API version: 2.4
 * Generated by: Swagger Codegen (https://github.com/swaggerapi/swaggercodegen.git)
 */

package hcsschema

type MemoryBackingPageSize string

// List of MemoryBackingPageSize
const (
	MemoryBackingPageSize_SMALL MemoryBackingPageSize = "Small"
	MemoryBackingPageSize_LARGE MemoryBackingPageSize = "Large"
	MemoryBackingPageSize_HUGE  MemoryBackingPageSize = "Huge"
)
