// Autogenerated code; DO NOT EDIT.

// Schema retrieved from branch 'rs_base2_hyp' and build '27645.1002.240617-2119'.

/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema

// MigrationOrigin : Where migration is initiated from
type MigrationOrigin string

// List of MigrationOrigin
const (
	MigrationOrigin_SOURCE      MigrationOrigin = "Source"
	MigrationOrigin_DESTINATION MigrationOrigin = "Destination"
)
