// Autogenerated code; DO NOT EDIT.

// Schema retrieved from branch 'fe_release' and build '20348.1.210507-1500'.

/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema

// VM specific processor feature requirements
type ProcessorFeatureSet struct {
	// Processor features
	ProcessorFeatures []ProcessorFeature `json:"ProcessorFeatures,omitempty"`
	// Xsave processor features
	XsaveProcessorFeatures []XsaveProcessorFeature `json:"XsaveProcessorFeatures,omitempty"`
	// Processor cache line flush size
	CacheLineFlushSize uint64 `json:"CacheLineFlushSize,omitempty"`
	// Processor physical address bits
	ImplementedPhysicalAddressBits uint64                       `json:"ImplementedPhysicalAddressBits,omitempty"`
	NonArchitecturalCoreSharing    *NonArchitecturalCoreSharing `json:"NonArchitecturalCoreSharing,omitempty"`
	// Processor enlightenment modifications
	EnlightenmentModifications []EnlightenmentModifications `json:"EnlightenmentModifications,omitempty"`
	ProcessorFeatureSetMode    *ProcessorFeatureSetMode     `json:"ProcessorFeatureSetMode,omitempty"`
}
