// Autogenerated code; DO NOT EDIT.

// Schema retrieved from branch 'fe_release' and build '20348.1.210507-1500'.

/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema

import (
	"encoding/json"
)

// This class is only necessary because JSON marshaling complains when we have two fields identical except for capitalization in the same class. Remove this once we stop supporting RS4.
type Rs4NetworkModifySettingRequest struct {
	RequestType *NetworkModifyRequestType `json:"RequestType,omitempty"`
	// Pattern: /^[0-9A-Fa-f]{8}-([0-9A-Fa-f]{4}-){3}[0-9A-Fa-f]{12}$/
	AdapterInstanceID string           `json:"AdapterInstanceID,omitempty"`
	Settings          *json.RawMessage `json:"Settings,omitempty"`
}
