// Autogenerated code; DO NOT EDIT.

/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema

// SgxLaunchControlMode : Flexible launch control (FLC) mode allows the guest's operating system to control which enclaves to be launched on the host. The specified MSR here is IA32_SGXLEPUBKEYHASH
type SgxLaunchControlMode string

// List of SgxLaunchControlMode
const (
	SgxLaunchControlMode_NO_ACCESS  SgxLaunchControlMode = "NoAccess"
	SgxLaunchControlMode_READ_ONLY  SgxLaunchControlMode = "ReadOnly"
	SgxLaunchControlMode_READ_WRITE SgxLaunchControlMode = "ReadWrite"
)
