// Autogenerated code; DO NOT EDIT.

// Schema retrieved from branch 'fe_release' and build '20348.1.210507-1500'.

/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema

// SystemPropertyType : Compute system property types. The properties will be returned as a Schema.Responses.System.Properties instance.
type SystemPropertyType string

// List of System_PropertyType
const (
	SystemPropertyType_MEMORY                          SystemPropertyType = "Memory"
	SystemPropertyType_GUEST_MEMORY                    SystemPropertyType = "GuestMemory"
	SystemPropertyType_CONTAINER_MEMORY                SystemPropertyType = "ContainerMemory"
	SystemPropertyType_CPU_GROUP                       SystemPropertyType = "CpuGroup"
	SystemPropertyType_STATISTICS                      SystemPropertyType = "Statistics"
	SystemPropertyType_PROCESS_LIST                    SystemPropertyType = "ProcessList"
	SystemPropertyType_TERMINATE_ON_LAST_HANDLE_CLOSED SystemPropertyType = "TerminateOnLastHandleClosed"
	SystemPropertyType_SYSTEM_GUID                     SystemPropertyType = "SystemGUID"
	SystemPropertyType_SHARED_MEMORY_REGION            SystemPropertyType = "SharedMemoryRegion"
	SystemPropertyType_SILO                            SystemPropertyType = "Silo"
	SystemPropertyType_GUEST_CONNECTION                SystemPropertyType = "GuestConnection"
	SystemPropertyType_COS_INDEX                       SystemPropertyType = "CosIndex"
	SystemPropertyType_RMID                            SystemPropertyType = "Rmid"
	SystemPropertyType_CACHE_STATS                     SystemPropertyType = "CacheStats"
	SystemPropertyType_IDLED_PROCESSORS                SystemPropertyType = "IdledProcessors"
	SystemPropertyType_CPU_FREQUENCY_POWER_CAP         SystemPropertyType = "CpuFrequencyPowerCap"
)
