// Autogenerated code; DO NOT EDIT.

/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema

type SystemExit struct {
	Detail    *SystemExitDetail `json:"Detail,omitempty"`
	Initiator *ExitInitiator    `json:"Initiator,omitempty"`
}
