// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v5.26.0
// source: github.com/Microsoft/hcsshim/pkg/ncproxy/ncproxygrpc/v1/networkconfigproxy.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HostComputeNetworkSettings_NetworkMode int32

const (
	HostComputeNetworkSettings_Transparent HostComputeNetworkSettings_NetworkMode = 0
	HostComputeNetworkSettings_NAT         HostComputeNetworkSettings_NetworkMode = 1
)

// Enum value maps for HostComputeNetworkSettings_NetworkMode.
var (
	HostComputeNetworkSettings_NetworkMode_name = map[int32]string{
		0: "Transparent",
		1: "NAT",
	}
	HostComputeNetworkSettings_NetworkMode_value = map[string]int32{
		"Transparent": 0,
		"NAT":         1,
	}
)

func (x HostComputeNetworkSettings_NetworkMode) Enum() *HostComputeNetworkSettings_NetworkMode {
	p := new(HostComputeNetworkSettings_NetworkMode)
	*p = x
	return p
}

func (x HostComputeNetworkSettings_NetworkMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HostComputeNetworkSettings_NetworkMode) Descriptor() protoreflect.EnumDescriptor {
	return file_github_com_Microsoft_hcsshim_pkg_ncproxy_ncproxygrpc_v1_networkconfigproxy_proto_enumTypes[0].Descriptor()
}

func (HostComputeNetworkSettings_NetworkMode) Type() protoreflect.EnumType {
	return &file_github_com_Microsoft_hcsshim_pkg_ncproxy_ncproxygrpc_v1_networkconfigproxy_proto_enumTypes[0]
}

func (x HostComputeNetworkSettings_NetworkMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HostComputeNetworkSettings_NetworkMode.Descriptor instead.
func (HostComputeNetworkSettings_NetworkMode) EnumDescriptor() ([]byte, []int) {
	return file_github_com_Microsoft_hcsshim_pkg_ncproxy_ncproxygrpc_v1_networkconfigproxy_proto_rawDescGZIP(), []int{9, 0}
}

type HostComputeNetworkSettings_IpamType int32

const (
	HostComputeNetworkSettings_Static HostComputeNetworkSettings_IpamType = 0
	HostComputeNetworkSettings_DHCP   HostComputeNetworkSettings_IpamType = 1
)

// Enum value maps for HostComputeNetworkSettings_IpamType.
var (
	HostComputeNetworkSettings_IpamType_name = map[int32]string{
		0: "Static",
		1: "DHCP",
	}
	HostComputeNetworkSettings_IpamType_value = map[string]int32{
		"Static": 0,
		"DHCP":   1,
	}
)

func (x HostComputeNetworkSettings_IpamType) Enum() *HostComputeNetworkSettings_IpamType {
	p := new(HostComputeNetworkSettings_IpamType)
	*p = x
	return p
}

func (x HostComputeNetworkSettings_IpamType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HostComputeNetworkSettings_IpamType) Descriptor() protoreflect.EnumDescriptor {
	return file_github_com_Microsoft_hcsshim_pkg_ncproxy_ncproxygrpc_v1_networkconfigproxy_proto_enumTypes[1].Descriptor()
}

func (HostComputeNetworkSettings_IpamType) Type() protoreflect.EnumType {
	return &file_github_com_Microsoft_hcsshim_pkg_ncproxy_ncproxygrpc_v1_networkconfigproxy_proto_enumTypes[1]
}

func (x HostComputeNetworkSettings_IpamType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HostComputeNetworkSettings_IpamType.Descriptor instead.
func (HostComputeNetworkSettings_IpamType) EnumDescriptor() ([]byte, []int) {
	return file_github_com_Microsoft_hcsshim_pkg_ncproxy_ncproxygrpc_v1_networkconfigproxy_proto_rawDescGZIP(), []int{9, 1}
}

type AddNICRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ContainerID      string                 `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	NicID            string                 `protobuf:"bytes,2,opt,name=nic_id,json=nicId,proto3" json:"nic_id,omitempty"`
	EndpointName     string                 `protobuf:"bytes,3,opt,name=endpoint_name,json=endpointName,proto3" json:"endpoint_name,omitempty"`
	EndpointSettings *EndpointSettings      `protobuf:"bytes,4,opt,name=endpoint_settings,json=endpointSettings,proto3" json:"endpoint_settings,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AddNICRequest) Reset() {
	*x = AddNICRequest{}
	mi := &file_github_com_Microsoft_hcsshim_pkg_ncproxy_ncproxygrpc_v1_networkconfigproxy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddNICRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddNICRequest) ProtoMessage() {}

func (x *AddNICRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_Microsoft_hcsshim_pkg_ncproxy_ncproxygrpc_v1_networkconfigproxy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddNICRequest.ProtoReflect.Descriptor instead.
func (*AddNICRequest) Descriptor() ([]byte, []int) {
	return file_github_com_Microsoft_hcsshim_pkg_ncproxy_ncproxygrpc_v1_networkconfigproxy_proto_rawDescGZIP(), []int{0}
}

func (x *AddNICRequest) GetContainerID() string {
	if x != nil {
		return x.ContainerID
	}
	return ""
}

func (x *AddNICRequest) GetNicID() string {
	if x != nil {
		return x.NicID
	}
	return ""
}

func (x *AddNICRequest) GetEndpointName() string {
	if x != nil {
		return x.EndpointName
	}
	return ""
}

func (x *AddNICRequest) GetEndpointSettings() *EndpointSettings {
	if x != nil {
		return x.EndpointSettings
	}
	return nil
}

type AddNICResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddNICResponse) Reset() {
	*x = AddNICResponse{}
	mi := &file_github_com_Microsoft_hcsshim_pkg_ncproxy_ncproxygrpc_v1_networkconfigproxy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddNICResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddNICResponse) ProtoMessage() {}

func (x *AddNICResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_Microsoft_hcsshim_pkg_ncproxy_ncproxygrpc_v1_networkconfigproxy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddNICResponse.ProtoReflect.Descriptor instead.
func (*AddNICResponse) Descriptor() ([]byte, []int) {
	return file_github_com_Microsoft_hcsshim_pkg_ncproxy_ncproxygrpc_v1_networkconfigproxy_proto_rawDescGZIP(), []int{1}
}

type ModifyNICRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ContainerID      string                 `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	NicID            string                 `protobuf:"bytes,2,opt,name=nic_id,json=nicId,proto3" json:"nic_id,omitempty"`
	EndpointName     string                 `protobuf:"bytes,3,opt,name=endpoint_name,json=endpointName,proto3" json:"endpoint_name,omitempty"`
	EndpointSettings *EndpointSettings      `protobuf:"bytes,4,opt,name=endpoint_settings,json=endpointSettings,proto3" json:"endpoint_settings,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ModifyNICRequest) Reset() {
	*x = ModifyNICRequest{}
	mi := &file_github_com_Microsoft_hcsshim_pkg_ncproxy_ncproxygrpc_v1_networkconfigproxy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModifyNICRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModifyNICRequest) ProtoMessage() {}

func (x *ModifyNICRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_Microsoft_hcsshim_pkg_ncproxy_ncproxygrpc_v1_networkconfigproxy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModifyNICRequest.ProtoReflect.Descriptor instead.
func (*ModifyNICRequest) Descriptor() ([]byte, []int) {
	return file_github_com_Microsoft_hcsshim_pkg_ncproxy_ncproxygrpc_v1_networkconfigproxy_proto_rawDescGZIP(), []int{2}
}

func (x *ModifyNICRequest) GetContainerID() string {
	if x != nil {
		return x.ContainerID
	}
	return ""
}

func (x *ModifyNICRequest) GetNicID() string {
	if x != nil {
		return x.NicID
	}
	return ""
}

func (x *ModifyNICRequest) GetEndpointName() string {
	if x != nil {
		return x.EndpointName
	}
	return ""
}

func (x *ModifyNICRequest) GetEndpointSettings() *EndpointSettings {
	if x != nil {
		return x.EndpointSettings
	}
	return nil
}

type ModifyNICResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModifyNICResponse) Reset() {
	*x = ModifyNICResponse{}
	mi := &file_github_com_Microsoft_hcsshim_pkg_ncproxy_ncproxygrpc_v1_networkconfigproxy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModifyNICResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModifyNICResponse) ProtoMessage() {}

func (x *ModifyNICResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_Microsoft_hcsshim_pkg_ncproxy_ncproxygrpc_v1_networkconfigproxy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModifyNICResponse.ProtoReflect.Descriptor instead.
func (*ModifyNICResponse) Descriptor() ([]byte, []int) {
	return file_github_com_Microsoft_hcsshim_pkg_ncproxy_ncproxygrpc_v1_networkconfigproxy_proto_rawDescGZIP(), []int{3}
}

type DeleteNICRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContainerID   string                 `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	NicID         string                 `protobuf:"bytes,2,opt,name=nic_id,json=nicId,proto3" json:"nic_id,omitempty"`
	EndpointName  string                 `protobuf:"bytes,3,opt,name=endpoint_name,json=endpointName,proto3" json:"endpoint_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteNICRequest) Reset() {
	*x = DeleteNICRequest{}
	mi := &file_github_com_Microsoft_hcsshim_pkg_ncproxy_ncproxygrpc_v1_networkconfigproxy_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteNICRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNICRequest) ProtoMessage() {}

func (x *DeleteNICRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_Microsoft_hcsshim_pkg_ncproxy_ncproxygrpc_v1_networkconfigproxy_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNICRequest.ProtoReflect.Descriptor instead.
func (*DeleteNICRequest) Descriptor() ([]byte, []int) {
	return file_github_com_Microsoft_hcsshim_pkg_ncproxy_ncproxygrpc_v1_networkconfigproxy_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteNICRequest) GetContainerID() string {
	if x != nil {
		return x.ContainerID
	}
	return ""
}

func (x *DeleteNICRequest) GetNicID() string {
	if x != nil {
		return x.NicID
	}
	return ""
}

func (x *DeleteNICRequest) GetEndpointName() string {
	if x != nil {
		return x.EndpointName
	}
	return ""
}

type DeleteNICResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteNICResponse) Reset() {
	*x = DeleteNICResponse{}
	mi := &file_github_com_Microsoft_hcsshim_pkg_ncproxy_ncproxygrpc_v1_networkconfigproxy_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteNICResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNICResponse) ProtoMessage() {}

func (x *DeleteNICResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_Microsoft_hcsshim_pkg_ncproxy_ncproxygrpc_v1_networkconfigproxy_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNICResponse.ProtoReflect.Descriptor instead.
func (*DeleteNICResponse) Descriptor() ([]byte, []int) {
	return file_github_com_Microsoft_hcsshim_pkg_ncproxy_ncproxygrpc_v1_networkconfigproxy_proto_rawDescGZIP(), []int{5}
}

type CreateNetworkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Network       *Network               `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNetworkRequest) Reset() {
	*x = CreateNetworkRequest{}
	mi := &file_github_com_Microsoft_hcsshim_pkg_ncproxy_ncproxygrpc_v1_networkconfigproxy_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNetworkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNetworkRequest) ProtoMessage() {}

func (x *CreateNetworkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_Microsoft_hcsshim_pkg_ncproxy_ncproxygrpc_v1_networkconfigproxy_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNetworkRequest.ProtoReflect.Descriptor instead.
func (*CreateNetworkRequest) Descriptor() ([]byte, []int) {
	return file_github_com_Microsoft_hcsshim_pkg_ncproxy_ncproxygrpc_v1_networkconfigproxy_proto_rawDescGZIP(), []int{6}
}

func (x *CreateNetworkRequest) GetNetwork() *Network {
	if x != nil {
		return x.Network
	}
	return nil
}

type Network struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Settings:
	//
	//	*Network_HcnNetwork
	//	*Network_NcproxyNetwork
	Settings      isNetwork_Settings `protobuf_oneof:"settings"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Network) Reset() {
	*x = Network{}
	mi := &file_github_com_Microsoft_hcsshim_pkg_ncproxy_ncproxygrpc_v1_networkconfigproxy_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Network) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Network) ProtoMessage() {}

func (x *Network) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_Microsoft_hcsshim_pkg_ncproxy_ncproxygrpc_v1_networkconfigproxy_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Network.ProtoReflect.Descriptor instead.
func (*Network) Descriptor() ([]byte, []int) {
	return file_github_com_Microsoft_hcsshim_pkg_ncproxy_ncproxygrpc_v1_networkconfigproxy_proto_rawDescGZIP(), []int{7}
}

func (x *Network) GetSettings() isNetwork_Settings {
	if x != nil {
		return x.Settings
	}
	return nil
}

func (x *Network) GetHcnNetwork() *HostComputeNetworkSettings {
	if x != nil {
		if x, ok := x.Settings.(*Network_HcnNetwork); ok {
			return x.HcnNetwork
		}
	}
	return nil
}

func (x *Network) GetNcproxyNetwork() *NCProxyNetworkSettings {
	if x != nil {
		if x, ok := x.Settings.(*Network_NcproxyNetwork); ok {
			return x.NcproxyNetwork
		}
	}
	return nil
}

type isNetwork_Settings interface {
	isNetwork_Settings()
}

type Network_HcnNetwork struct {
	HcnNetwork *HostComputeNetworkSettings `protobuf:"bytes,1,opt,name=hcn_network,json=hcnNetwork,proto3,oneof"`
}

type Network_NcproxyNetwork struct {
	NcproxyNetwork *NCProxyNetworkSettings `protobuf:"bytes,2,opt,name=ncproxy_network,json=ncproxyNetwork,proto3,oneof"`
}

func (*Network_HcnNetwork) isNetwork_Settings() {}

func (*Network_NcproxyNetwork) isNetwork_Settings() {}

type NCProxyNetworkSettings struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NCProxyNetworkSettings) Reset() {
	*x = NCProxyNetworkSettings{}
	mi := &file_github_com_Microsoft_hcsshim_pkg_ncproxy_ncproxygrpc_v1_networkconfigproxy_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NCProxyNetworkSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NCProxyNetworkSettings) ProtoMessage() {}

func (x *NCProxyNetworkSettings) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_Microsoft_hcsshim_pkg_ncproxy_ncproxygrpc_v1_networkconfigproxy_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NCProxyNetworkSettings.ProtoReflect.Descriptor instead.
func (*NCProxyNetworkSettings) Descriptor() ([]byte, []int) {
	return file_github_com_Microsoft_hcsshim_pkg_ncproxy_ncproxygrpc_v1_networkconfigproxy_proto_rawDescGZIP(), []int{8}
}

func (x *NCProxyNetworkSettings) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type HostComputeNetworkSettings struct {
	state                     protoimpl.MessageState                 `protogen:"open.v1"`
	Name                      string                                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Mode                      HostComputeNetworkSettings_NetworkMode `protobuf:"varint,2,opt,name=mode,proto3,enum=ncproxygrpc.v1.HostComputeNetworkSettings_NetworkMode" json:"mode,omitempty"`
	SwitchName                string                                 `protobuf:"bytes,3,opt,name=switch_name,json=switchName,proto3" json:"switch_name,omitempty"`
	IpamType                  HostComputeNetworkSettings_IpamType    `protobuf:"varint,4,opt,name=ipam_type,json=ipamType,proto3,enum=ncproxygrpc.v1.HostComputeNetworkSettings_IpamType" json:"ipam_type,omitempty"`
	SubnetIpaddressPrefix     []string                               `protobuf:"bytes,5,rep,name=subnet_ipaddress_prefix,json=subnetIpaddressPrefix,proto3" json:"subnet_ipaddress_prefix,omitempty"`
	DefaultGateway            string                                 `protobuf:"bytes,6,opt,name=default_gateway,json=defaultGateway,proto3" json:"default_gateway,omitempty"`
	SubnetIpaddressPrefixIpv6 []string                               `protobuf:"bytes,7,rep,name=subnet_ipaddress_prefix_ipv6,json=subnetIpaddressPrefixIpv6,proto3" json:"subnet_ipaddress_prefix_ipv6,omitempty"`
	DefaultGatewayIpv6        string                                 `protobuf:"bytes,8,opt,name=default_gateway_ipv6,json=defaultGatewayIpv6,proto3" json:"default_gateway_ipv6,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *HostComputeNetworkSettings) Reset() {
	*x = HostComputeNetworkSettings{}
	mi := &file_github_com_Microsoft_hcsshim_pkg_ncproxy_ncproxygrpc_v1_networkconfigproxy_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostComputeNetworkSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostComputeNetworkSettings) ProtoMessage() {}

func (x *HostComputeNetworkSettings) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_Microsoft_hcsshim_pkg_ncproxy_ncproxygrpc_v1_networkconfigproxy_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostComputeNetworkSettings.ProtoReflect.Descriptor instead.
func (*HostComputeNetworkSettings) Descriptor() ([]byte, []int) {
	return file_github_com_Microsoft_hcsshim_pkg_ncproxy_ncproxygrpc_v1_networkconfigproxy_proto_rawDescGZIP(), []int{9}
}

func (x *HostComputeNetworkSettings) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *HostComputeNetworkSettings) GetMode() HostComputeNetworkSettings_NetworkMode {
	if x != nil {
		return x.Mode
	}
	return HostComputeNetworkSettings_Transparent
}

func (x *HostComputeNetworkSettings) GetSwitchName() string {
	if x != nil {
		return x.SwitchName
	}
	return ""
}

func (x *HostComputeNetworkSettings) GetIpamType() HostComputeNetworkSettings_IpamType {
	if x != nil {
		return x.IpamType
	}
	return HostComputeNetworkSettings_Static
}

func (x *HostComputeNetworkSettings) GetSubnetIpaddressPrefix() []string {
	if x != nil {
		return x.SubnetIpaddressPrefix
	}
	return nil
}

func (x *HostComputeNetworkSettings) GetDefaultGateway() string {
	if x != nil {
		return x.DefaultGateway
	}
	return ""
}

func (x *HostComputeNetworkSettings) GetSubnetIpaddressPrefixIpv6() []string {
	if x != nil {
		return x.SubnetIpaddressPrefixIpv6
	}
	return nil
}

func (x *HostComputeNetworkSettings) GetDefaultGatewayIpv6() string {
	if x != nil {
		return x.DefaultGatewayIpv6
	}
	return ""
}

type CreateNetworkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNetworkResponse) Reset() {
	*x = CreateNetworkResponse{}
	mi := &file_github_com_Microsoft_hcsshim_pkg_ncproxy_ncproxygrpc_v1_networkconfigproxy_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNetworkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNetworkResponse) ProtoMessage() {}

func (x *CreateNetworkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_Microsoft_hcsshim_pkg_ncproxy_ncproxygrpc_v1_networkconfigproxy_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNetworkResponse.ProtoReflect.Descriptor instead.
func (*CreateNetworkResponse) Descriptor() ([]byte, []int) {
	return file_github_com_Microsoft_hcsshim_pkg_ncproxy_ncproxygrpc_v1_networkconfigproxy_proto_rawDescGZIP(), []int{10}
}

func (x *CreateNetworkResponse) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

type PortNameEndpointPolicySetting struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PortName      string                 `protobuf:"bytes,1,opt,name=port_name,json=portName,proto3" json:"port_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PortNameEndpointPolicySetting) Reset() {
	*x = PortNameEndpointPolicySetting{}
	mi := &file_github_com_Microsoft_hcsshim_pkg_ncproxy_ncproxygrpc_v1_networkconfigproxy_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortNameEndpointPolicySetting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortNameEndpointPolicySetting) ProtoMessage() {}

func (x *PortNameEndpointPolicySetting) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_Microsoft_hcsshim_pkg_ncproxy_ncproxygrpc_v1_networkconfigproxy_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortNameEndpointPolicySetting.ProtoReflect.Descriptor instead.
func (*PortNameEndpointPolicySetting) Descriptor() ([]byte, []int) {
	return file_github_com_Microsoft_hcsshim_pkg_ncproxy_ncproxygrpc_v1_networkconfigproxy_proto_rawDescGZIP(), []int{11}
}

func (x *PortNameEndpointPolicySetting) GetPortName() string {
	if x != nil {
		return x.PortName
	}
	return ""
}

type IovEndpointPolicySetting struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	IovOffloadWeight    uint32                 `protobuf:"varint,1,opt,name=iov_offload_weight,json=iovOffloadWeight,proto3" json:"iov_offload_weight,omitempty"`
	QueuePairsRequested uint32                 `protobuf:"varint,2,opt,name=queue_pairs_requested,json=queuePairsRequested,proto3" json:"queue_pairs_requested,omitempty"`
	InterruptModeration uint32                 `protobuf:"varint,3,opt,name=interrupt_moderation,json=interruptModeration,proto3" json:"interrupt_moderation,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *IovEndpointPolicySetting) Reset() {
	*x = IovEndpointPolicySetting{}
	mi := &file_github_com_Microsoft_hcsshim_pkg_ncproxy_ncproxygrpc_v1_networkconfigproxy_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IovEndpointPolicySetting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IovEndpointPolicySetting) ProtoMessage() {}

func (x *IovEndpointPolicySetting) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_Microsoft_hcsshim_pkg_ncproxy_ncproxygrpc_v1_networkconfigproxy_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IovEndpointPolicySetting.ProtoReflect.Descriptor instead.
func (*IovEndpointPolicySetting) Descriptor() ([]byte, []int) {
	return file_github_com_Microsoft_hcsshim_pkg_ncproxy_ncproxygrpc_v1_networkconfigproxy_proto_rawDescGZIP(), []int{12}
}

func (x *IovEndpointPolicySetting) GetIovOffloadWeight() uint32 {
	if x != nil {
		return x.IovOffloadWeight
	}
	return 0
}

func (x *IovEndpointPolicySetting) GetQueuePairsRequested() uint32 {
	if x != nil {
		return x.QueuePairsRequested
	}
	return 0
}

func (x *IovEndpointPolicySetting) GetInterruptModeration() uint32 {
	if x != nil {
		return x.InterruptModeration
	}
	return 0
}

type DnsSetting struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerIpAddrs []string               `protobuf:"bytes,1,rep,name=server_ip_addrs,json=serverIpAddrs,proto3" json:"server_ip_addrs,omitempty"`
	Domain        string                 `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain,omitempty"`
	Search        []string               `protobuf:"bytes,3,rep,name=search,proto3" json:"search,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DnsSetting) Reset() {
	*x = DnsSetting{}
	mi := &file_github_com_Microsoft_hcsshim_pkg_ncproxy_ncproxygrpc_v1_networkconfigproxy_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DnsSetting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DnsSetting) ProtoMessage() {}

func (x *DnsSetting) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_Microsoft_hcsshim_pkg_ncproxy_ncproxygrpc_v1_networkconfigproxy_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DnsSetting.ProtoReflect.Descriptor instead.
func (*DnsSetting) Descriptor() ([]byte, []int) {
	return file_github_com_Microsoft_hcsshim_pkg_ncproxy_ncproxygrpc_v1_networkconfigproxy_proto_rawDescGZIP(), []int{13}
}

func (x *DnsSetting) GetServerIpAddrs() []string {
	if x != nil {
		return x.ServerIpAddrs
	}
	return nil
}

func (x *DnsSetting) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *DnsSetting) GetSearch() []string {
	if x != nil {
		return x.Search
	}
	return nil
}

type CreateEndpointRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	EndpointSettings *EndpointSettings      `protobuf:"bytes,1,opt,name=endpoint_settings,json=endpointSettings,proto3" json:"endpoint_settings,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateEndpointRequest) Reset() {
	*x = CreateEndpointRequest{}
	mi := &file_github_com_Microsoft_hcsshim_pkg_ncproxy_ncproxygrpc_v1_networkconfigproxy_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEndpointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEndpointRequest) ProtoMessage() {}

func (x *CreateEndpointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_Microsoft_hcsshim_pkg_ncproxy_ncproxygrpc_v1_networkconfigproxy_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEndpointRequest.ProtoReflect.Descriptor instead.
func (*CreateEndpointRequest) Descriptor() ([]byte, []int) {
	return file_github_com_Microsoft_hcsshim_pkg_ncproxy_ncproxygrpc_v1_networkconfigproxy_proto_rawDescGZIP(), []int{14}
}

func (x *CreateEndpointRequest) GetEndpointSettings() *EndpointSettings {
	if x != nil {
		return x.EndpointSettings
	}
	return nil
}

type EndpointSettings struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Settings:
	//
	//	*EndpointSettings_HcnEndpoint
	//	*EndpointSettings_NcproxyEndpoint
	Settings      isEndpointSettings_Settings `protobuf_oneof:"settings"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndpointSettings) Reset() {
	*x = EndpointSettings{}
	mi := &file_github_com_Microsoft_hcsshim_pkg_ncproxy_ncproxygrpc_v1_networkconfigproxy_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndpointSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndpointSettings) ProtoMessage() {}

func (x *EndpointSettings) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_Microsoft_hcsshim_pkg_ncproxy_ncproxygrpc_v1_networkconfigproxy_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndpointSettings.ProtoReflect.Descriptor instead.
func (*EndpointSettings) Descriptor() ([]byte, []int) {
	return file_github_com_Microsoft_hcsshim_pkg_ncproxy_ncproxygrpc_v1_networkconfigproxy_proto_rawDescGZIP(), []int{15}
}

func (x *EndpointSettings) GetSettings() isEndpointSettings_Settings {
	if x != nil {
		return x.Settings
	}
	return nil
}

func (x *EndpointSettings) GetHcnEndpoint() *HcnEndpointSettings {
	if x != nil {
		if x, ok := x.Settings.(*EndpointSettings_HcnEndpoint); ok {
			return x.HcnEndpoint
		}
	}
	return nil
}

func (x *EndpointSettings) GetNcproxyEndpoint() *NCProxyEndpointSettings {
	if x != nil {
		if x, ok := x.Settings.(*EndpointSettings_NcproxyEndpoint); ok {
			return x.NcproxyEndpoint
		}
	}
	return nil
}

type isEndpointSettings_Settings interface {
	isEndpointSettings_Settings()
}

type EndpointSettings_HcnEndpoint struct {
	HcnEndpoint *HcnEndpointSettings `protobuf:"bytes,1,opt,name=hcn_endpoint,json=hcnEndpoint,proto3,oneof"`
}

type EndpointSettings_NcproxyEndpoint struct {
	NcproxyEndpoint *NCProxyEndpointSettings `protobuf:"bytes,2,opt,name=ncproxy_endpoint,json=ncproxyEndpoint,proto3,oneof"`
}

func (*EndpointSettings_HcnEndpoint) isEndpointSettings_Settings() {}

func (*EndpointSettings_NcproxyEndpoint) isEndpointSettings_Settings() {}

type HcnEndpointResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	ID            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Settings      *HcnEndpointSettings   `protobuf:"bytes,3,opt,name=settings,proto3" json:"settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HcnEndpointResponse) Reset() {
	*x = HcnEndpointResponse{}
	mi := &file_github_com_Microsoft_hcsshim_pkg_ncproxy_ncproxygrpc_v1_networkconfigproxy_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HcnEndpointResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HcnEndpointResponse) ProtoMessage() {}

func (x *HcnEndpointResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_Microsoft_hcsshim_pkg_ncproxy_ncproxygrpc_v1_networkconfigproxy_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HcnEndpointResponse.ProtoReflect.Descriptor instead.
func (*HcnEndpointResponse) Descriptor() ([]byte, []int) {
	return file_github_com_Microsoft_hcsshim_pkg_ncproxy_ncproxygrpc_v1_networkconfigproxy_proto_rawDescGZIP(), []int{16}
}

func (x *HcnEndpointResponse) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *HcnEndpointResponse) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *HcnEndpointResponse) GetSettings() *HcnEndpointSettings {
	if x != nil {
		return x.Settings
	}
	return nil
}

type HcnEndpointSettings struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Name                    string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Macaddress              string                 `protobuf:"bytes,2,opt,name=macaddress,proto3" json:"macaddress,omitempty"`
	Ipaddress               string                 `protobuf:"bytes,3,opt,name=ipaddress,proto3" json:"ipaddress,omitempty"`
	IpaddressPrefixlength   uint32                 `protobuf:"varint,4,opt,name=ipaddress_prefixlength,json=ipaddressPrefixlength,proto3" json:"ipaddress_prefixlength,omitempty"`
	NetworkName             string                 `protobuf:"bytes,5,opt,name=network_name,json=networkName,proto3" json:"network_name,omitempty"`
	Policies                *HcnEndpointPolicies   `protobuf:"bytes,6,opt,name=policies,proto3" json:"policies,omitempty"`
	DnsSetting              *DnsSetting            `protobuf:"bytes,7,opt,name=dns_setting,json=dnsSetting,proto3" json:"dns_setting,omitempty"`
	Ipv6Address             string                 `protobuf:"bytes,8,opt,name=ipv6address,proto3" json:"ipv6address,omitempty"`
	Ipv6AddressPrefixlength uint32                 `protobuf:"varint,9,opt,name=ipv6address_prefixlength,json=ipv6addressPrefixlength,proto3" json:"ipv6address_prefixlength,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *HcnEndpointSettings) Reset() {
	*x = HcnEndpointSettings{}
	mi := &file_github_com_Microsoft_hcsshim_pkg_ncproxy_ncproxygrpc_v1_networkconfigproxy_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HcnEndpointSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HcnEndpointSettings) ProtoMessage() {}

func (x *HcnEndpointSettings) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_Microsoft_hcsshim_pkg_ncproxy_ncproxygrpc_v1_networkconfigproxy_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HcnEndpointSettings.ProtoReflect.Descriptor instead.
func (*HcnEndpointSettings) Descriptor() ([]byte, []int) {
	return file_github_com_Microsoft_hcsshim_pkg_ncproxy_ncproxygrpc_v1_networkconfigproxy_proto_rawDescGZIP(), []int{17}
}

func (x *HcnEndpointSettings) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *HcnEndpointSettings) GetMacaddress() string {
	if x != nil {
		return x.Macaddress
	}
	return ""
}

func (x *HcnEndpointSettings) GetIpaddress() string {
	if x != nil {
		return x.Ipaddress
	}
	return ""
}

func (x *HcnEndpointSettings) GetIpaddressPrefixlength() uint32 {
	if x != nil {
		return x.IpaddressPrefixlength
	}
	return 0
}

func (x *HcnEndpointSettings) GetNetworkName() string {
	if x != nil {
		return x.NetworkName
	}
	return ""
}

func (x *HcnEndpointSettings) GetPolicies() *HcnEndpointPolicies {
	if x != nil {
		return x.Policies
	}
	return nil
}

func (x *HcnEndpointSettings) GetDnsSetting() *DnsSetting {
	if x != nil {
		return x.DnsSetting
	}
	return nil
}

func (x *HcnEndpointSettings) GetIpv6Address() string {
	if x != nil {
		return x.Ipv6Address
	}
	return ""
}

func (x *HcnEndpointSettings) GetIpv6AddressPrefixlength() uint32 {
	if x != nil {
		return x.Ipv6AddressPrefixlength
	}
	return 0
}

type HcnEndpointPolicies struct {
	state                 protoimpl.MessageState         `protogen:"open.v1"`
	PortnamePolicySetting *PortNameEndpointPolicySetting `protobuf:"bytes,1,opt,name=portname_policy_setting,json=portnamePolicySetting,proto3" json:"portname_policy_setting,omitempty"`
	IovPolicySettings     *IovEndpointPolicySetting      `protobuf:"bytes,2,opt,name=iov_policy_settings,json=iovPolicySettings,proto3" json:"iov_policy_settings,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *HcnEndpointPolicies) Reset() {
	*x = HcnEndpointPolicies{}
	mi := &file_github_com_Microsoft_hcsshim_pkg_ncproxy_ncproxygrpc_v1_networkconfigproxy_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HcnEndpointPolicies) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HcnEndpointPolicies) ProtoMessage() {}

func (x *HcnEndpointPolicies) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_Microsoft_hcsshim_pkg_ncproxy_ncproxygrpc_v1_networkconfigproxy_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HcnEndpointPolicies.ProtoReflect.Descriptor instead.
func (*HcnEndpointPolicies) Descriptor() ([]byte, []int) {
	return file_github_com_Microsoft_hcsshim_pkg_ncproxy_ncproxygrpc_v1_networkconfigproxy_proto_rawDescGZIP(), []int{18}
}

func (x *HcnEndpointPolicies) GetPortnamePolicySetting() *PortNameEndpointPolicySetting {
	if x != nil {
		return x.PortnamePolicySetting
	}
	return nil
}

func (x *HcnEndpointPolicies) GetIovPolicySettings() *IovEndpointPolicySetting {
	if x != nil {
		return x.IovPolicySettings
	}
	return nil
}

type NCProxyEndpointSettings struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Name                  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Macaddress            string                 `protobuf:"bytes,2,opt,name=macaddress,proto3" json:"macaddress,omitempty"`
	Ipaddress             string                 `protobuf:"bytes,3,opt,name=ipaddress,proto3" json:"ipaddress,omitempty"`
	IpaddressPrefixlength uint32                 `protobuf:"varint,4,opt,name=ipaddress_prefixlength,json=ipaddressPrefixlength,proto3" json:"ipaddress_prefixlength,omitempty"`
	NetworkName           string                 `protobuf:"bytes,5,opt,name=network_name,json=networkName,proto3" json:"network_name,omitempty"`
	DefaultGateway        string                 `protobuf:"bytes,6,opt,name=default_gateway,json=defaultGateway,proto3" json:"default_gateway,omitempty"`
	// Types that are valid to be assigned to DeviceDetails:
	//
	//	*NCProxyEndpointSettings_PciDeviceDetails
	DeviceDetails           isNCProxyEndpointSettings_DeviceDetails `protobuf_oneof:"device_details"`
	Ipv6Address             string                                  `protobuf:"bytes,8,opt,name=ipv6address,proto3" json:"ipv6address,omitempty"`
	Ipv6AddressPrefixlength string                                  `protobuf:"bytes,9,opt,name=ipv6address_prefixlength,json=ipv6addressPrefixlength,proto3" json:"ipv6address_prefixlength,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *NCProxyEndpointSettings) Reset() {
	*x = NCProxyEndpointSettings{}
	mi := &file_github_com_Microsoft_hcsshim_pkg_ncproxy_ncproxygrpc_v1_networkconfigproxy_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NCProxyEndpointSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NCProxyEndpointSettings) ProtoMessage() {}

func (x *NCProxyEndpointSettings) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_Microsoft_hcsshim_pkg_ncproxy_ncproxygrpc_v1_networkconfigproxy_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NCProxyEndpointSettings.ProtoReflect.Descriptor instead.
func (*NCProxyEndpointSettings) Descriptor() ([]byte, []int) {
	return file_github_com_Microsoft_hcsshim_pkg_ncproxy_ncproxygrpc_v1_networkconfigproxy_proto_rawDescGZIP(), []int{19}
}

func (x *NCProxyEndpointSettings) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NCProxyEndpointSettings) GetMacaddress() string {
	if x != nil {
		return x.Macaddress
	}
	return ""
}

func (x *NCProxyEndpointSettings) GetIpaddress() string {
	if x != nil {
		return x.Ipaddress
	}
	return ""
}

func (x *NCProxyEndpointSettings) GetIpaddressPrefixlength() uint32 {
	if x != nil {
		return x.IpaddressPrefixlength
	}
	return 0
}

func (x *NCProxyEndpointSettings) GetNetworkName() string {
	if x != nil {
		return x.NetworkName
	}
	return ""
}

func (x *NCProxyEndpointSettings) GetDefaultGateway() string {
	if x != nil {
		return x.DefaultGateway
	}
	return ""
}

func (x *NCProxyEndpointSettings) GetDeviceDetails() isNCProxyEndpointSettings_DeviceDetails {
	if x != nil {
		return x.DeviceDetails
	}
	return nil
}

func (x *NCProxyEndpointSettings) GetPciDeviceDetails() *PCIDeviceDetails {
	if x != nil {
		if x, ok := x.DeviceDetails.(*NCProxyEndpointSettings_PciDeviceDetails); ok {
			return x.PciDeviceDetails
		}
	}
	return nil
}

func (x *NCProxyEndpointSettings) GetIpv6Address() string {
	if x != nil {
		return x.Ipv6Address
	}
	return ""
}

func (x *NCProxyEndpointSettings) GetIpv6AddressPrefixlength() string {
	if x != nil {
		return x.Ipv6AddressPrefixlength
	}
	return ""
}

type isNCProxyEndpointSettings_DeviceDetails interface {
	isNCProxyEndpointSettings_DeviceDetails()
}

type NCProxyEndpointSettings_PciDeviceDetails struct {
	PciDeviceDetails *PCIDeviceDetails `protobuf:"bytes,7,opt,name=pci_device_details,json=pciDeviceDetails,proto3,oneof"`
}

func (*NCProxyEndpointSettings_PciDeviceDetails) isNCProxyEndpointSettings_DeviceDetails() {}

type PCIDeviceDetails struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	DeviceID             string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	VirtualFunctionIndex uint32                 `protobuf:"varint,2,opt,name=virtual_function_index,json=virtualFunctionIndex,proto3" json:"virtual_function_index,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *PCIDeviceDetails) Reset() {
	*x = PCIDeviceDetails{}
	mi := &file_github_com_Microsoft_hcsshim_pkg_ncproxy_ncproxygrpc_v1_networkconfigproxy_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PCIDeviceDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PCIDeviceDetails) ProtoMessage() {}

func (x *PCIDeviceDetails) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_Microsoft_hcsshim_pkg_ncproxy_ncproxygrpc_v1_networkconfigproxy_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PCIDeviceDetails.ProtoReflect.Descriptor instead.
func (*PCIDeviceDetails) Descriptor() ([]byte, []int) {
	return file_github_com_Microsoft_hcsshim_pkg_ncproxy_ncproxygrpc_v1_networkconfigproxy_proto_rawDescGZIP(), []int{20}
}

func (x *PCIDeviceDetails) GetDeviceID() string {
	if x != nil {
		return x.DeviceID
	}
	return ""
}

func (x *PCIDeviceDetails) GetVirtualFunctionIndex() uint32 {
	if x != nil {
		return x.VirtualFunctionIndex
	}
	return 0
}

type CreateEndpointResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEndpointResponse) Reset() {
	*x = CreateEndpointResponse{}
	mi := &file_github_com_Microsoft_hcsshim_pkg_ncproxy_ncproxygrpc_v1_networkconfigproxy_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEndpointResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEndpointResponse) ProtoMessage() {}

func (x *CreateEndpointResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_Microsoft_hcsshim_pkg_ncproxy_ncproxygrpc_v1_networkconfigproxy_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEndpointResponse.ProtoReflect.Descriptor instead.
func (*CreateEndpointResponse) Descriptor() ([]byte, []int) {
	return file_github_com_Microsoft_hcsshim_pkg_ncproxy_ncproxygrpc_v1_networkconfigproxy_proto_rawDescGZIP(), []int{21}
}

func (x *CreateEndpointResponse) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

type AddEndpointRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	NamespaceID   string                 `protobuf:"bytes,2,opt,name=namespace_id,json=namespaceId,proto3" json:"namespace_id,omitempty"`
	AttachToHost  bool                   `protobuf:"varint,3,opt,name=attach_to_host,json=attachToHost,proto3" json:"attach_to_host,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddEndpointRequest) Reset() {
	*x = AddEndpointRequest{}
	mi := &file_github_com_Microsoft_hcsshim_pkg_ncproxy_ncproxygrpc_v1_networkconfigproxy_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddEndpointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddEndpointRequest) ProtoMessage() {}

func (x *AddEndpointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_Microsoft_hcsshim_pkg_ncproxy_ncproxygrpc_v1_networkconfigproxy_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddEndpointRequest.ProtoReflect.Descriptor instead.
func (*AddEndpointRequest) Descriptor() ([]byte, []int) {
	return file_github_com_Microsoft_hcsshim_pkg_ncproxy_ncproxygrpc_v1_networkconfigproxy_proto_rawDescGZIP(), []int{22}
}

func (x *AddEndpointRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddEndpointRequest) GetNamespaceID() string {
	if x != nil {
		return x.NamespaceID
	}
	return ""
}

func (x *AddEndpointRequest) GetAttachToHost() bool {
	if x != nil {
		return x.AttachToHost
	}
	return false
}

type AddEndpointResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddEndpointResponse) Reset() {
	*x = AddEndpointResponse{}
	mi := &file_github_com_Microsoft_hcsshim_pkg_ncproxy_ncproxygrpc_v1_networkconfigproxy_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddEndpointResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddEndpointResponse) ProtoMessage() {}

func (x *AddEndpointResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_Microsoft_hcsshim_pkg_ncproxy_ncproxygrpc_v1_networkconfigproxy_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddEndpointResponse.ProtoReflect.Descriptor instead.
func (*AddEndpointResponse) Descriptor() ([]byte, []int) {
	return file_github_com_Microsoft_hcsshim_pkg_ncproxy_ncproxygrpc_v1_networkconfigproxy_proto_rawDescGZIP(), []int{23}
}

type DeleteEndpointRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEndpointRequest) Reset() {
	*x = DeleteEndpointRequest{}
	mi := &file_github_com_Microsoft_hcsshim_pkg_ncproxy_ncproxygrpc_v1_networkconfigproxy_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEndpointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEndpointRequest) ProtoMessage() {}

func (x *DeleteEndpointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_Microsoft_hcsshim_pkg_ncproxy_ncproxygrpc_v1_networkconfigproxy_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEndpointRequest.ProtoReflect.Descriptor instead.
func (*DeleteEndpointRequest) Descriptor() ([]byte, []int) {
	return file_github_com_Microsoft_hcsshim_pkg_ncproxy_ncproxygrpc_v1_networkconfigproxy_proto_rawDescGZIP(), []int{24}
}

func (x *DeleteEndpointRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeleteEndpointResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEndpointResponse) Reset() {
	*x = DeleteEndpointResponse{}
	mi := &file_github_com_Microsoft_hcsshim_pkg_ncproxy_ncproxygrpc_v1_networkconfigproxy_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEndpointResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEndpointResponse) ProtoMessage() {}

func (x *DeleteEndpointResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_Microsoft_hcsshim_pkg_ncproxy_ncproxygrpc_v1_networkconfigproxy_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEndpointResponse.ProtoReflect.Descriptor instead.
func (*DeleteEndpointResponse) Descriptor() ([]byte, []int) {
	return file_github_com_Microsoft_hcsshim_pkg_ncproxy_ncproxygrpc_v1_networkconfigproxy_proto_rawDescGZIP(), []int{25}
}

type DeleteNetworkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteNetworkRequest) Reset() {
	*x = DeleteNetworkRequest{}
	mi := &file_github_com_Microsoft_hcsshim_pkg_ncproxy_ncproxygrpc_v1_networkconfigproxy_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteNetworkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNetworkRequest) ProtoMessage() {}

func (x *DeleteNetworkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_Microsoft_hcsshim_pkg_ncproxy_ncproxygrpc_v1_networkconfigproxy_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNetworkRequest.ProtoReflect.Descriptor instead.
func (*DeleteNetworkRequest) Descriptor() ([]byte, []int) {
	return file_github_com_Microsoft_hcsshim_pkg_ncproxy_ncproxygrpc_v1_networkconfigproxy_proto_rawDescGZIP(), []int{26}
}

func (x *DeleteNetworkRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeleteNetworkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteNetworkResponse) Reset() {
	*x = DeleteNetworkResponse{}
	mi := &file_github_com_Microsoft_hcsshim_pkg_ncproxy_ncproxygrpc_v1_networkconfigproxy_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteNetworkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNetworkResponse) ProtoMessage() {}

func (x *DeleteNetworkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_Microsoft_hcsshim_pkg_ncproxy_ncproxygrpc_v1_networkconfigproxy_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNetworkResponse.ProtoReflect.Descriptor instead.
func (*DeleteNetworkResponse) Descriptor() ([]byte, []int) {
	return file_github_com_Microsoft_hcsshim_pkg_ncproxy_ncproxygrpc_v1_networkconfigproxy_proto_rawDescGZIP(), []int{27}
}

type GetEndpointRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEndpointRequest) Reset() {
	*x = GetEndpointRequest{}
	mi := &file_github_com_Microsoft_hcsshim_pkg_ncproxy_ncproxygrpc_v1_networkconfigproxy_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEndpointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEndpointRequest) ProtoMessage() {}

func (x *GetEndpointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_Microsoft_hcsshim_pkg_ncproxy_ncproxygrpc_v1_networkconfigproxy_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEndpointRequest.ProtoReflect.Descriptor instead.
func (*GetEndpointRequest) Descriptor() ([]byte, []int) {
	return file_github_com_Microsoft_hcsshim_pkg_ncproxy_ncproxygrpc_v1_networkconfigproxy_proto_rawDescGZIP(), []int{28}
}

func (x *GetEndpointRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetEndpointResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	ID            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Endpoint      *EndpointSettings      `protobuf:"bytes,3,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEndpointResponse) Reset() {
	*x = GetEndpointResponse{}
	mi := &file_github_com_Microsoft_hcsshim_pkg_ncproxy_ncproxygrpc_v1_networkconfigproxy_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEndpointResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEndpointResponse) ProtoMessage() {}

func (x *GetEndpointResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_Microsoft_hcsshim_pkg_ncproxy_ncproxygrpc_v1_networkconfigproxy_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEndpointResponse.ProtoReflect.Descriptor instead.
func (*GetEndpointResponse) Descriptor() ([]byte, []int) {
	return file_github_com_Microsoft_hcsshim_pkg_ncproxy_ncproxygrpc_v1_networkconfigproxy_proto_rawDescGZIP(), []int{29}
}

func (x *GetEndpointResponse) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *GetEndpointResponse) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *GetEndpointResponse) GetEndpoint() *EndpointSettings {
	if x != nil {
		return x.Endpoint
	}
	return nil
}

type GetNetworkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNetworkRequest) Reset() {
	*x = GetNetworkRequest{}
	mi := &file_github_com_Microsoft_hcsshim_pkg_ncproxy_ncproxygrpc_v1_networkconfigproxy_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNetworkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNetworkRequest) ProtoMessage() {}

func (x *GetNetworkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_Microsoft_hcsshim_pkg_ncproxy_ncproxygrpc_v1_networkconfigproxy_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNetworkRequest.ProtoReflect.Descriptor instead.
func (*GetNetworkRequest) Descriptor() ([]byte, []int) {
	return file_github_com_Microsoft_hcsshim_pkg_ncproxy_ncproxygrpc_v1_networkconfigproxy_proto_rawDescGZIP(), []int{30}
}

func (x *GetNetworkRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetNetworkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Network       *Network               `protobuf:"bytes,2,opt,name=network,proto3" json:"network,omitempty"`
	MacRange      *MacRange              `protobuf:"bytes,3,opt,name=macRange,proto3" json:"macRange,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNetworkResponse) Reset() {
	*x = GetNetworkResponse{}
	mi := &file_github_com_Microsoft_hcsshim_pkg_ncproxy_ncproxygrpc_v1_networkconfigproxy_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNetworkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNetworkResponse) ProtoMessage() {}

func (x *GetNetworkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_Microsoft_hcsshim_pkg_ncproxy_ncproxygrpc_v1_networkconfigproxy_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNetworkResponse.ProtoReflect.Descriptor instead.
func (*GetNetworkResponse) Descriptor() ([]byte, []int) {
	return file_github_com_Microsoft_hcsshim_pkg_ncproxy_ncproxygrpc_v1_networkconfigproxy_proto_rawDescGZIP(), []int{31}
}

func (x *GetNetworkResponse) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *GetNetworkResponse) GetNetwork() *Network {
	if x != nil {
		return x.Network
	}
	return nil
}

func (x *GetNetworkResponse) GetMacRange() *MacRange {
	if x != nil {
		return x.MacRange
	}
	return nil
}

type MacRange struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	StartMacAddress string                 `protobuf:"bytes,1,opt,name=startMacAddress,proto3" json:"startMacAddress,omitempty"`
	EndMacAddress   string                 `protobuf:"bytes,2,opt,name=endMacAddress,proto3" json:"endMacAddress,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MacRange) Reset() {
	*x = MacRange{}
	mi := &file_github_com_Microsoft_hcsshim_pkg_ncproxy_ncproxygrpc_v1_networkconfigproxy_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MacRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MacRange) ProtoMessage() {}

func (x *MacRange) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_Microsoft_hcsshim_pkg_ncproxy_ncproxygrpc_v1_networkconfigproxy_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MacRange.ProtoReflect.Descriptor instead.
func (*MacRange) Descriptor() ([]byte, []int) {
	return file_github_com_Microsoft_hcsshim_pkg_ncproxy_ncproxygrpc_v1_networkconfigproxy_proto_rawDescGZIP(), []int{32}
}

func (x *MacRange) GetStartMacAddress() string {
	if x != nil {
		return x.StartMacAddress
	}
	return ""
}

func (x *MacRange) GetEndMacAddress() string {
	if x != nil {
		return x.EndMacAddress
	}
	return ""
}

type GetEndpointsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEndpointsRequest) Reset() {
	*x = GetEndpointsRequest{}
	mi := &file_github_com_Microsoft_hcsshim_pkg_ncproxy_ncproxygrpc_v1_networkconfigproxy_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEndpointsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEndpointsRequest) ProtoMessage() {}

func (x *GetEndpointsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_Microsoft_hcsshim_pkg_ncproxy_ncproxygrpc_v1_networkconfigproxy_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEndpointsRequest.ProtoReflect.Descriptor instead.
func (*GetEndpointsRequest) Descriptor() ([]byte, []int) {
	return file_github_com_Microsoft_hcsshim_pkg_ncproxy_ncproxygrpc_v1_networkconfigproxy_proto_rawDescGZIP(), []int{33}
}

type GetEndpointsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Endpoints     []*GetEndpointResponse `protobuf:"bytes,1,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEndpointsResponse) Reset() {
	*x = GetEndpointsResponse{}
	mi := &file_github_com_Microsoft_hcsshim_pkg_ncproxy_ncproxygrpc_v1_networkconfigproxy_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEndpointsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEndpointsResponse) ProtoMessage() {}

func (x *GetEndpointsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_Microsoft_hcsshim_pkg_ncproxy_ncproxygrpc_v1_networkconfigproxy_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEndpointsResponse.ProtoReflect.Descriptor instead.
func (*GetEndpointsResponse) Descriptor() ([]byte, []int) {
	return file_github_com_Microsoft_hcsshim_pkg_ncproxy_ncproxygrpc_v1_networkconfigproxy_proto_rawDescGZIP(), []int{34}
}

func (x *GetEndpointsResponse) GetEndpoints() []*GetEndpointResponse {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

type GetNetworksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNetworksRequest) Reset() {
	*x = GetNetworksRequest{}
	mi := &file_github_com_Microsoft_hcsshim_pkg_ncproxy_ncproxygrpc_v1_networkconfigproxy_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNetworksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNetworksRequest) ProtoMessage() {}

func (x *GetNetworksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_Microsoft_hcsshim_pkg_ncproxy_ncproxygrpc_v1_networkconfigproxy_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNetworksRequest.ProtoReflect.Descriptor instead.
func (*GetNetworksRequest) Descriptor() ([]byte, []int) {
	return file_github_com_Microsoft_hcsshim_pkg_ncproxy_ncproxygrpc_v1_networkconfigproxy_proto_rawDescGZIP(), []int{35}
}

type GetNetworksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Networks      []*GetNetworkResponse  `protobuf:"bytes,1,rep,name=networks,proto3" json:"networks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNetworksResponse) Reset() {
	*x = GetNetworksResponse{}
	mi := &file_github_com_Microsoft_hcsshim_pkg_ncproxy_ncproxygrpc_v1_networkconfigproxy_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNetworksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNetworksResponse) ProtoMessage() {}

func (x *GetNetworksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_Microsoft_hcsshim_pkg_ncproxy_ncproxygrpc_v1_networkconfigproxy_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNetworksResponse.ProtoReflect.Descriptor instead.
func (*GetNetworksResponse) Descriptor() ([]byte, []int) {
	return file_github_com_Microsoft_hcsshim_pkg_ncproxy_ncproxygrpc_v1_networkconfigproxy_proto_rawDescGZIP(), []int{36}
}

func (x *GetNetworksResponse) GetNetworks() []*GetNetworkResponse {
	if x != nil {
		return x.Networks
	}
	return nil
}

var File_github_com_Microsoft_hcsshim_pkg_ncproxy_ncproxygrpc_v1_networkconfigproxy_proto protoreflect.FileDescriptor

const file_github_com_Microsoft_hcsshim_pkg_ncproxy_ncproxygrpc_v1_networkconfigproxy_proto_rawDesc = "" +
	"\n" +
	"Pgithub.com/Microsoft/hcsshim/pkg/ncproxy/ncproxygrpc/v1/networkconfigproxy.proto\x12\x0encproxygrpc.v1\"\xbd\x01\n" +
	"\rAddNICRequest\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\x12\x15\n" +
	"\x06nic_id\x18\x02 \x01(\tR\x05nicId\x12#\n" +
	"\rendpoint_name\x18\x03 \x01(\tR\fendpointName\x12M\n" +
	"\x11endpoint_settings\x18\x04 \x01(\v2 .ncproxygrpc.v1.EndpointSettingsR\x10endpointSettings\"\x10\n" +
	"\x0eAddNICResponse\"\xc0\x01\n" +
	"\x10ModifyNICRequest\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\x12\x15\n" +
	"\x06nic_id\x18\x02 \x01(\tR\x05nicId\x12#\n" +
	"\rendpoint_name\x18\x03 \x01(\tR\fendpointName\x12M\n" +
	"\x11endpoint_settings\x18\x04 \x01(\v2 .ncproxygrpc.v1.EndpointSettingsR\x10endpointSettings\"\x13\n" +
	"\x11ModifyNICResponse\"q\n" +
	"\x10DeleteNICRequest\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\x12\x15\n" +
	"\x06nic_id\x18\x02 \x01(\tR\x05nicId\x12#\n" +
	"\rendpoint_name\x18\x03 \x01(\tR\fendpointName\"\x13\n" +
	"\x11DeleteNICResponse\"I\n" +
	"\x14CreateNetworkRequest\x121\n" +
	"\anetwork\x18\x01 \x01(\v2\x17.ncproxygrpc.v1.NetworkR\anetwork\"\xb7\x01\n" +
	"\aNetwork\x12M\n" +
	"\vhcn_network\x18\x01 \x01(\v2*.ncproxygrpc.v1.HostComputeNetworkSettingsH\x00R\n" +
	"hcnNetwork\x12Q\n" +
	"\x0fncproxy_network\x18\x02 \x01(\v2&.ncproxygrpc.v1.NCProxyNetworkSettingsH\x00R\x0encproxyNetworkB\n" +
	"\n" +
	"\bsettings\",\n" +
	"\x16NCProxyNetworkSettings\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x8e\x04\n" +
	"\x1aHostComputeNetworkSettings\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12J\n" +
	"\x04mode\x18\x02 \x01(\x0e26.ncproxygrpc.v1.HostComputeNetworkSettings.NetworkModeR\x04mode\x12\x1f\n" +
	"\vswitch_name\x18\x03 \x01(\tR\n" +
	"switchName\x12P\n" +
	"\tipam_type\x18\x04 \x01(\x0e23.ncproxygrpc.v1.HostComputeNetworkSettings.IpamTypeR\bipamType\x126\n" +
	"\x17subnet_ipaddress_prefix\x18\x05 \x03(\tR\x15subnetIpaddressPrefix\x12'\n" +
	"\x0fdefault_gateway\x18\x06 \x01(\tR\x0edefaultGateway\x12?\n" +
	"\x1csubnet_ipaddress_prefix_ipv6\x18\a \x03(\tR\x19subnetIpaddressPrefixIpv6\x120\n" +
	"\x14default_gateway_ipv6\x18\b \x01(\tR\x12defaultGatewayIpv6\"'\n" +
	"\vNetworkMode\x12\x0f\n" +
	"\vTransparent\x10\x00\x12\a\n" +
	"\x03NAT\x10\x01\" \n" +
	"\bIpamType\x12\n" +
	"\n" +
	"\x06Static\x10\x00\x12\b\n" +
	"\x04DHCP\x10\x01\"'\n" +
	"\x15CreateNetworkResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"<\n" +
	"\x1dPortNameEndpointPolicySetting\x12\x1b\n" +
	"\tport_name\x18\x01 \x01(\tR\bportName\"\xaf\x01\n" +
	"\x18IovEndpointPolicySetting\x12,\n" +
	"\x12iov_offload_weight\x18\x01 \x01(\rR\x10iovOffloadWeight\x122\n" +
	"\x15queue_pairs_requested\x18\x02 \x01(\rR\x13queuePairsRequested\x121\n" +
	"\x14interrupt_moderation\x18\x03 \x01(\rR\x13interruptModeration\"d\n" +
	"\n" +
	"DnsSetting\x12&\n" +
	"\x0fserver_ip_addrs\x18\x01 \x03(\tR\rserverIpAddrs\x12\x16\n" +
	"\x06domain\x18\x02 \x01(\tR\x06domain\x12\x16\n" +
	"\x06search\x18\x03 \x03(\tR\x06search\"f\n" +
	"\x15CreateEndpointRequest\x12M\n" +
	"\x11endpoint_settings\x18\x01 \x01(\v2 .ncproxygrpc.v1.EndpointSettingsR\x10endpointSettings\"\xbe\x01\n" +
	"\x10EndpointSettings\x12H\n" +
	"\fhcn_endpoint\x18\x01 \x01(\v2#.ncproxygrpc.v1.HcnEndpointSettingsH\x00R\vhcnEndpoint\x12T\n" +
	"\x10ncproxy_endpoint\x18\x02 \x01(\v2'.ncproxygrpc.v1.NCProxyEndpointSettingsH\x00R\x0fncproxyEndpointB\n" +
	"\n" +
	"\bsettings\"\x84\x01\n" +
	"\x13HcnEndpointResponse\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12?\n" +
	"\bsettings\x18\x03 \x01(\v2#.ncproxygrpc.v1.HcnEndpointSettingsR\bsettings\"\x9c\x03\n" +
	"\x13HcnEndpointSettings\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1e\n" +
	"\n" +
	"macaddress\x18\x02 \x01(\tR\n" +
	"macaddress\x12\x1c\n" +
	"\tipaddress\x18\x03 \x01(\tR\tipaddress\x125\n" +
	"\x16ipaddress_prefixlength\x18\x04 \x01(\rR\x15ipaddressPrefixlength\x12!\n" +
	"\fnetwork_name\x18\x05 \x01(\tR\vnetworkName\x12?\n" +
	"\bpolicies\x18\x06 \x01(\v2#.ncproxygrpc.v1.HcnEndpointPoliciesR\bpolicies\x12;\n" +
	"\vdns_setting\x18\a \x01(\v2\x1a.ncproxygrpc.v1.DnsSettingR\n" +
	"dnsSetting\x12 \n" +
	"\vipv6address\x18\b \x01(\tR\vipv6address\x129\n" +
	"\x18ipv6address_prefixlength\x18\t \x01(\rR\x17ipv6addressPrefixlength\"\xdc\x01\n" +
	"\x13HcnEndpointPolicies\x12e\n" +
	"\x17portname_policy_setting\x18\x01 \x01(\v2-.ncproxygrpc.v1.PortNameEndpointPolicySettingR\x15portnamePolicySetting\x12X\n" +
	"\x13iov_policy_settings\x18\x02 \x01(\v2(.ncproxygrpc.v1.IovEndpointPolicySettingR\x11iovPolicySettingsJ\x04\b\x03\x10\b\"\xaf\x03\n" +
	"\x17NCProxyEndpointSettings\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1e\n" +
	"\n" +
	"macaddress\x18\x02 \x01(\tR\n" +
	"macaddress\x12\x1c\n" +
	"\tipaddress\x18\x03 \x01(\tR\tipaddress\x125\n" +
	"\x16ipaddress_prefixlength\x18\x04 \x01(\rR\x15ipaddressPrefixlength\x12!\n" +
	"\fnetwork_name\x18\x05 \x01(\tR\vnetworkName\x12'\n" +
	"\x0fdefault_gateway\x18\x06 \x01(\tR\x0edefaultGateway\x12P\n" +
	"\x12pci_device_details\x18\a \x01(\v2 .ncproxygrpc.v1.PCIDeviceDetailsH\x00R\x10pciDeviceDetails\x12 \n" +
	"\vipv6address\x18\b \x01(\tR\vipv6address\x129\n" +
	"\x18ipv6address_prefixlength\x18\t \x01(\tR\x17ipv6addressPrefixlengthB\x10\n" +
	"\x0edevice_details\"e\n" +
	"\x10PCIDeviceDetails\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x124\n" +
	"\x16virtual_function_index\x18\x02 \x01(\rR\x14virtualFunctionIndex\"(\n" +
	"\x16CreateEndpointResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"q\n" +
	"\x12AddEndpointRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12!\n" +
	"\fnamespace_id\x18\x02 \x01(\tR\vnamespaceId\x12$\n" +
	"\x0eattach_to_host\x18\x03 \x01(\bR\fattachToHost\"\x15\n" +
	"\x13AddEndpointResponse\"+\n" +
	"\x15DeleteEndpointRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x18\n" +
	"\x16DeleteEndpointResponse\"*\n" +
	"\x14DeleteNetworkRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x17\n" +
	"\x15DeleteNetworkResponse\"(\n" +
	"\x12GetEndpointRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x81\x01\n" +
	"\x13GetEndpointResponse\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12<\n" +
	"\bendpoint\x18\x03 \x01(\v2 .ncproxygrpc.v1.EndpointSettingsR\bendpoint\"'\n" +
	"\x11GetNetworkRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x8d\x01\n" +
	"\x12GetNetworkResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x121\n" +
	"\anetwork\x18\x02 \x01(\v2\x17.ncproxygrpc.v1.NetworkR\anetwork\x124\n" +
	"\bmacRange\x18\x03 \x01(\v2\x18.ncproxygrpc.v1.MacRangeR\bmacRange\"Z\n" +
	"\bMacRange\x12(\n" +
	"\x0fstartMacAddress\x18\x01 \x01(\tR\x0fstartMacAddress\x12$\n" +
	"\rendMacAddress\x18\x02 \x01(\tR\rendMacAddress\"\x15\n" +
	"\x13GetEndpointsRequest\"Y\n" +
	"\x14GetEndpointsResponse\x12A\n" +
	"\tendpoints\x18\x01 \x03(\v2#.ncproxygrpc.v1.GetEndpointResponseR\tendpoints\"\x14\n" +
	"\x12GetNetworksRequest\"U\n" +
	"\x13GetNetworksResponse\x12>\n" +
	"\bnetworks\x18\x01 \x03(\v2\".ncproxygrpc.v1.GetNetworkResponseR\bnetworks2\xcf\b\n" +
	"\x12NetworkConfigProxy\x12I\n" +
	"\x06AddNIC\x12\x1d.ncproxygrpc.v1.AddNICRequest\x1a\x1e.ncproxygrpc.v1.AddNICResponse\"\x00\x12R\n" +
	"\tModifyNIC\x12 .ncproxygrpc.v1.ModifyNICRequest\x1a!.ncproxygrpc.v1.ModifyNICResponse\"\x00\x12R\n" +
	"\tDeleteNIC\x12 .ncproxygrpc.v1.DeleteNICRequest\x1a!.ncproxygrpc.v1.DeleteNICResponse\"\x00\x12^\n" +
	"\rCreateNetwork\x12$.ncproxygrpc.v1.CreateNetworkRequest\x1a%.ncproxygrpc.v1.CreateNetworkResponse\"\x00\x12a\n" +
	"\x0eCreateEndpoint\x12%.ncproxygrpc.v1.CreateEndpointRequest\x1a&.ncproxygrpc.v1.CreateEndpointResponse\"\x00\x12X\n" +
	"\vAddEndpoint\x12\".ncproxygrpc.v1.AddEndpointRequest\x1a#.ncproxygrpc.v1.AddEndpointResponse\"\x00\x12a\n" +
	"\x0eDeleteEndpoint\x12%.ncproxygrpc.v1.DeleteEndpointRequest\x1a&.ncproxygrpc.v1.DeleteEndpointResponse\"\x00\x12^\n" +
	"\rDeleteNetwork\x12$.ncproxygrpc.v1.DeleteNetworkRequest\x1a%.ncproxygrpc.v1.DeleteNetworkResponse\"\x00\x12X\n" +
	"\vGetEndpoint\x12\".ncproxygrpc.v1.GetEndpointRequest\x1a#.ncproxygrpc.v1.GetEndpointResponse\"\x00\x12U\n" +
	"\n" +
	"GetNetwork\x12!.ncproxygrpc.v1.GetNetworkRequest\x1a\".ncproxygrpc.v1.GetNetworkResponse\"\x00\x12[\n" +
	"\fGetEndpoints\x12#.ncproxygrpc.v1.GetEndpointsRequest\x1a$.ncproxygrpc.v1.GetEndpointsResponse\"\x00\x12X\n" +
	"\vGetNetworks\x12\".ncproxygrpc.v1.GetNetworksRequest\x1a#.ncproxygrpc.v1.GetNetworksResponse\"\x00B9Z7github.com/Microsoft/hcsshim/pkg/ncproxy/ncproxygrpc/v1b\x06proto3"

var (
	file_github_com_Microsoft_hcsshim_pkg_ncproxy_ncproxygrpc_v1_networkconfigproxy_proto_rawDescOnce sync.Once
	file_github_com_Microsoft_hcsshim_pkg_ncproxy_ncproxygrpc_v1_networkconfigproxy_proto_rawDescData []byte
)

func file_github_com_Microsoft_hcsshim_pkg_ncproxy_ncproxygrpc_v1_networkconfigproxy_proto_rawDescGZIP() []byte {
	file_github_com_Microsoft_hcsshim_pkg_ncproxy_ncproxygrpc_v1_networkconfigproxy_proto_rawDescOnce.Do(func() {
		file_github_com_Microsoft_hcsshim_pkg_ncproxy_ncproxygrpc_v1_networkconfigproxy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_github_com_Microsoft_hcsshim_pkg_ncproxy_ncproxygrpc_v1_networkconfigproxy_proto_rawDesc), len(file_github_com_Microsoft_hcsshim_pkg_ncproxy_ncproxygrpc_v1_networkconfigproxy_proto_rawDesc)))
	})
	return file_github_com_Microsoft_hcsshim_pkg_ncproxy_ncproxygrpc_v1_networkconfigproxy_proto_rawDescData
}

var file_github_com_Microsoft_hcsshim_pkg_ncproxy_ncproxygrpc_v1_networkconfigproxy_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_github_com_Microsoft_hcsshim_pkg_ncproxy_ncproxygrpc_v1_networkconfigproxy_proto_msgTypes = make([]protoimpl.MessageInfo, 37)
var file_github_com_Microsoft_hcsshim_pkg_ncproxy_ncproxygrpc_v1_networkconfigproxy_proto_goTypes = []any{
	(HostComputeNetworkSettings_NetworkMode)(0), // 0: ncproxygrpc.v1.HostComputeNetworkSettings.NetworkMode
	(HostComputeNetworkSettings_IpamType)(0),    // 1: ncproxygrpc.v1.HostComputeNetworkSettings.IpamType
	(*AddNICRequest)(nil),                       // 2: ncproxygrpc.v1.AddNICRequest
	(*AddNICResponse)(nil),                      // 3: ncproxygrpc.v1.AddNICResponse
	(*ModifyNICRequest)(nil),                    // 4: ncproxygrpc.v1.ModifyNICRequest
	(*ModifyNICResponse)(nil),                   // 5: ncproxygrpc.v1.ModifyNICResponse
	(*DeleteNICRequest)(nil),                    // 6: ncproxygrpc.v1.DeleteNICRequest
	(*DeleteNICResponse)(nil),                   // 7: ncproxygrpc.v1.DeleteNICResponse
	(*CreateNetworkRequest)(nil),                // 8: ncproxygrpc.v1.CreateNetworkRequest
	(*Network)(nil),                             // 9: ncproxygrpc.v1.Network
	(*NCProxyNetworkSettings)(nil),              // 10: ncproxygrpc.v1.NCProxyNetworkSettings
	(*HostComputeNetworkSettings)(nil),          // 11: ncproxygrpc.v1.HostComputeNetworkSettings
	(*CreateNetworkResponse)(nil),               // 12: ncproxygrpc.v1.CreateNetworkResponse
	(*PortNameEndpointPolicySetting)(nil),       // 13: ncproxygrpc.v1.PortNameEndpointPolicySetting
	(*IovEndpointPolicySetting)(nil),            // 14: ncproxygrpc.v1.IovEndpointPolicySetting
	(*DnsSetting)(nil),                          // 15: ncproxygrpc.v1.DnsSetting
	(*CreateEndpointRequest)(nil),               // 16: ncproxygrpc.v1.CreateEndpointRequest
	(*EndpointSettings)(nil),                    // 17: ncproxygrpc.v1.EndpointSettings
	(*HcnEndpointResponse)(nil),                 // 18: ncproxygrpc.v1.HcnEndpointResponse
	(*HcnEndpointSettings)(nil),                 // 19: ncproxygrpc.v1.HcnEndpointSettings
	(*HcnEndpointPolicies)(nil),                 // 20: ncproxygrpc.v1.HcnEndpointPolicies
	(*NCProxyEndpointSettings)(nil),             // 21: ncproxygrpc.v1.NCProxyEndpointSettings
	(*PCIDeviceDetails)(nil),                    // 22: ncproxygrpc.v1.PCIDeviceDetails
	(*CreateEndpointResponse)(nil),              // 23: ncproxygrpc.v1.CreateEndpointResponse
	(*AddEndpointRequest)(nil),                  // 24: ncproxygrpc.v1.AddEndpointRequest
	(*AddEndpointResponse)(nil),                 // 25: ncproxygrpc.v1.AddEndpointResponse
	(*DeleteEndpointRequest)(nil),               // 26: ncproxygrpc.v1.DeleteEndpointRequest
	(*DeleteEndpointResponse)(nil),              // 27: ncproxygrpc.v1.DeleteEndpointResponse
	(*DeleteNetworkRequest)(nil),                // 28: ncproxygrpc.v1.DeleteNetworkRequest
	(*DeleteNetworkResponse)(nil),               // 29: ncproxygrpc.v1.DeleteNetworkResponse
	(*GetEndpointRequest)(nil),                  // 30: ncproxygrpc.v1.GetEndpointRequest
	(*GetEndpointResponse)(nil),                 // 31: ncproxygrpc.v1.GetEndpointResponse
	(*GetNetworkRequest)(nil),                   // 32: ncproxygrpc.v1.GetNetworkRequest
	(*GetNetworkResponse)(nil),                  // 33: ncproxygrpc.v1.GetNetworkResponse
	(*MacRange)(nil),                            // 34: ncproxygrpc.v1.MacRange
	(*GetEndpointsRequest)(nil),                 // 35: ncproxygrpc.v1.GetEndpointsRequest
	(*GetEndpointsResponse)(nil),                // 36: ncproxygrpc.v1.GetEndpointsResponse
	(*GetNetworksRequest)(nil),                  // 37: ncproxygrpc.v1.GetNetworksRequest
	(*GetNetworksResponse)(nil),                 // 38: ncproxygrpc.v1.GetNetworksResponse
}
var file_github_com_Microsoft_hcsshim_pkg_ncproxy_ncproxygrpc_v1_networkconfigproxy_proto_depIdxs = []int32{
	17, // 0: ncproxygrpc.v1.AddNICRequest.endpoint_settings:type_name -> ncproxygrpc.v1.EndpointSettings
	17, // 1: ncproxygrpc.v1.ModifyNICRequest.endpoint_settings:type_name -> ncproxygrpc.v1.EndpointSettings
	9,  // 2: ncproxygrpc.v1.CreateNetworkRequest.network:type_name -> ncproxygrpc.v1.Network
	11, // 3: ncproxygrpc.v1.Network.hcn_network:type_name -> ncproxygrpc.v1.HostComputeNetworkSettings
	10, // 4: ncproxygrpc.v1.Network.ncproxy_network:type_name -> ncproxygrpc.v1.NCProxyNetworkSettings
	0,  // 5: ncproxygrpc.v1.HostComputeNetworkSettings.mode:type_name -> ncproxygrpc.v1.HostComputeNetworkSettings.NetworkMode
	1,  // 6: ncproxygrpc.v1.HostComputeNetworkSettings.ipam_type:type_name -> ncproxygrpc.v1.HostComputeNetworkSettings.IpamType
	17, // 7: ncproxygrpc.v1.CreateEndpointRequest.endpoint_settings:type_name -> ncproxygrpc.v1.EndpointSettings
	19, // 8: ncproxygrpc.v1.EndpointSettings.hcn_endpoint:type_name -> ncproxygrpc.v1.HcnEndpointSettings
	21, // 9: ncproxygrpc.v1.EndpointSettings.ncproxy_endpoint:type_name -> ncproxygrpc.v1.NCProxyEndpointSettings
	19, // 10: ncproxygrpc.v1.HcnEndpointResponse.settings:type_name -> ncproxygrpc.v1.HcnEndpointSettings
	20, // 11: ncproxygrpc.v1.HcnEndpointSettings.policies:type_name -> ncproxygrpc.v1.HcnEndpointPolicies
	15, // 12: ncproxygrpc.v1.HcnEndpointSettings.dns_setting:type_name -> ncproxygrpc.v1.DnsSetting
	13, // 13: ncproxygrpc.v1.HcnEndpointPolicies.portname_policy_setting:type_name -> ncproxygrpc.v1.PortNameEndpointPolicySetting
	14, // 14: ncproxygrpc.v1.HcnEndpointPolicies.iov_policy_settings:type_name -> ncproxygrpc.v1.IovEndpointPolicySetting
	22, // 15: ncproxygrpc.v1.NCProxyEndpointSettings.pci_device_details:type_name -> ncproxygrpc.v1.PCIDeviceDetails
	17, // 16: ncproxygrpc.v1.GetEndpointResponse.endpoint:type_name -> ncproxygrpc.v1.EndpointSettings
	9,  // 17: ncproxygrpc.v1.GetNetworkResponse.network:type_name -> ncproxygrpc.v1.Network
	34, // 18: ncproxygrpc.v1.GetNetworkResponse.macRange:type_name -> ncproxygrpc.v1.MacRange
	31, // 19: ncproxygrpc.v1.GetEndpointsResponse.endpoints:type_name -> ncproxygrpc.v1.GetEndpointResponse
	33, // 20: ncproxygrpc.v1.GetNetworksResponse.networks:type_name -> ncproxygrpc.v1.GetNetworkResponse
	2,  // 21: ncproxygrpc.v1.NetworkConfigProxy.AddNIC:input_type -> ncproxygrpc.v1.AddNICRequest
	4,  // 22: ncproxygrpc.v1.NetworkConfigProxy.ModifyNIC:input_type -> ncproxygrpc.v1.ModifyNICRequest
	6,  // 23: ncproxygrpc.v1.NetworkConfigProxy.DeleteNIC:input_type -> ncproxygrpc.v1.DeleteNICRequest
	8,  // 24: ncproxygrpc.v1.NetworkConfigProxy.CreateNetwork:input_type -> ncproxygrpc.v1.CreateNetworkRequest
	16, // 25: ncproxygrpc.v1.NetworkConfigProxy.CreateEndpoint:input_type -> ncproxygrpc.v1.CreateEndpointRequest
	24, // 26: ncproxygrpc.v1.NetworkConfigProxy.AddEndpoint:input_type -> ncproxygrpc.v1.AddEndpointRequest
	26, // 27: ncproxygrpc.v1.NetworkConfigProxy.DeleteEndpoint:input_type -> ncproxygrpc.v1.DeleteEndpointRequest
	28, // 28: ncproxygrpc.v1.NetworkConfigProxy.DeleteNetwork:input_type -> ncproxygrpc.v1.DeleteNetworkRequest
	30, // 29: ncproxygrpc.v1.NetworkConfigProxy.GetEndpoint:input_type -> ncproxygrpc.v1.GetEndpointRequest
	32, // 30: ncproxygrpc.v1.NetworkConfigProxy.GetNetwork:input_type -> ncproxygrpc.v1.GetNetworkRequest
	35, // 31: ncproxygrpc.v1.NetworkConfigProxy.GetEndpoints:input_type -> ncproxygrpc.v1.GetEndpointsRequest
	37, // 32: ncproxygrpc.v1.NetworkConfigProxy.GetNetworks:input_type -> ncproxygrpc.v1.GetNetworksRequest
	3,  // 33: ncproxygrpc.v1.NetworkConfigProxy.AddNIC:output_type -> ncproxygrpc.v1.AddNICResponse
	5,  // 34: ncproxygrpc.v1.NetworkConfigProxy.ModifyNIC:output_type -> ncproxygrpc.v1.ModifyNICResponse
	7,  // 35: ncproxygrpc.v1.NetworkConfigProxy.DeleteNIC:output_type -> ncproxygrpc.v1.DeleteNICResponse
	12, // 36: ncproxygrpc.v1.NetworkConfigProxy.CreateNetwork:output_type -> ncproxygrpc.v1.CreateNetworkResponse
	23, // 37: ncproxygrpc.v1.NetworkConfigProxy.CreateEndpoint:output_type -> ncproxygrpc.v1.CreateEndpointResponse
	25, // 38: ncproxygrpc.v1.NetworkConfigProxy.AddEndpoint:output_type -> ncproxygrpc.v1.AddEndpointResponse
	27, // 39: ncproxygrpc.v1.NetworkConfigProxy.DeleteEndpoint:output_type -> ncproxygrpc.v1.DeleteEndpointResponse
	29, // 40: ncproxygrpc.v1.NetworkConfigProxy.DeleteNetwork:output_type -> ncproxygrpc.v1.DeleteNetworkResponse
	31, // 41: ncproxygrpc.v1.NetworkConfigProxy.GetEndpoint:output_type -> ncproxygrpc.v1.GetEndpointResponse
	33, // 42: ncproxygrpc.v1.NetworkConfigProxy.GetNetwork:output_type -> ncproxygrpc.v1.GetNetworkResponse
	36, // 43: ncproxygrpc.v1.NetworkConfigProxy.GetEndpoints:output_type -> ncproxygrpc.v1.GetEndpointsResponse
	38, // 44: ncproxygrpc.v1.NetworkConfigProxy.GetNetworks:output_type -> ncproxygrpc.v1.GetNetworksResponse
	33, // [33:45] is the sub-list for method output_type
	21, // [21:33] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() {
	file_github_com_Microsoft_hcsshim_pkg_ncproxy_ncproxygrpc_v1_networkconfigproxy_proto_init()
}
func file_github_com_Microsoft_hcsshim_pkg_ncproxy_ncproxygrpc_v1_networkconfigproxy_proto_init() {
	if File_github_com_Microsoft_hcsshim_pkg_ncproxy_ncproxygrpc_v1_networkconfigproxy_proto != nil {
		return
	}
	file_github_com_Microsoft_hcsshim_pkg_ncproxy_ncproxygrpc_v1_networkconfigproxy_proto_msgTypes[7].OneofWrappers = []any{
		(*Network_HcnNetwork)(nil),
		(*Network_NcproxyNetwork)(nil),
	}
	file_github_com_Microsoft_hcsshim_pkg_ncproxy_ncproxygrpc_v1_networkconfigproxy_proto_msgTypes[15].OneofWrappers = []any{
		(*EndpointSettings_HcnEndpoint)(nil),
		(*EndpointSettings_NcproxyEndpoint)(nil),
	}
	file_github_com_Microsoft_hcsshim_pkg_ncproxy_ncproxygrpc_v1_networkconfigproxy_proto_msgTypes[19].OneofWrappers = []any{
		(*NCProxyEndpointSettings_PciDeviceDetails)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_github_com_Microsoft_hcsshim_pkg_ncproxy_ncproxygrpc_v1_networkconfigproxy_proto_rawDesc), len(file_github_com_Microsoft_hcsshim_pkg_ncproxy_ncproxygrpc_v1_networkconfigproxy_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   37,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_github_com_Microsoft_hcsshim_pkg_ncproxy_ncproxygrpc_v1_networkconfigproxy_proto_goTypes,
		DependencyIndexes: file_github_com_Microsoft_hcsshim_pkg_ncproxy_ncproxygrpc_v1_networkconfigproxy_proto_depIdxs,
		EnumInfos:         file_github_com_Microsoft_hcsshim_pkg_ncproxy_ncproxygrpc_v1_networkconfigproxy_proto_enumTypes,
		MessageInfos:      file_github_com_Microsoft_hcsshim_pkg_ncproxy_ncproxygrpc_v1_networkconfigproxy_proto_msgTypes,
	}.Build()
	File_github_com_Microsoft_hcsshim_pkg_ncproxy_ncproxygrpc_v1_networkconfigproxy_proto = out.File
	file_github_com_Microsoft_hcsshim_pkg_ncproxy_ncproxygrpc_v1_networkconfigproxy_proto_goTypes = nil
	file_github_com_Microsoft_hcsshim_pkg_ncproxy_ncproxygrpc_v1_networkconfigproxy_proto_depIdxs = nil
}
