// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.26.0
// source: github.com/Microsoft/hcsshim/internal/controller/pod/save/payload.proto

package save

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Payload is the migration payload owned by a single pod controller. It is
// the top-level message wrapped in an [anypb.Any] when handed off between
// source and destination shims. The embedded network controller and
// container controllers are carried as opaque [anypb.Any] payloads so each
// child controller fully owns its own schema.
type Payload struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// schema_version is bumped whenever a field's semantics change. The
	// destination MUST reject states whose version it does not recognise.
	SchemaVersion uint32 `protobuf:"varint,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	// pod_id is the pod identifier.
	PodID string `protobuf:"bytes,2,opt,name=pod_id,json=podId,proto3" json:"pod_id,omitempty"`
	// gcs_pod_id is the pod identifier as known by the GCS inside the
	// guest, which may differ from pod_id.
	GcsPodID string `protobuf:"bytes,3,opt,name=gcs_pod_id,json=gcsPodId,proto3" json:"gcs_pod_id,omitempty"`
	// network is the per-pod network controller's [anypb.Any] envelope.
	Network *anypb.Any `protobuf:"bytes,4,opt,name=network,proto3" json:"network,omitempty"`
	// containers is the set of container [Payload] envelopes for this pod,
	// one [anypb.Any] per container controller.
	Containers    []*anypb.Any `protobuf:"bytes,5,rep,name=containers,proto3" json:"containers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Payload) Reset() {
	*x = Payload{}
	mi := &file_github_com_Microsoft_hcsshim_internal_controller_pod_save_payload_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Payload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payload) ProtoMessage() {}

func (x *Payload) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_Microsoft_hcsshim_internal_controller_pod_save_payload_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payload.ProtoReflect.Descriptor instead.
func (*Payload) Descriptor() ([]byte, []int) {
	return file_github_com_Microsoft_hcsshim_internal_controller_pod_save_payload_proto_rawDescGZIP(), []int{0}
}

func (x *Payload) GetSchemaVersion() uint32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

func (x *Payload) GetPodID() string {
	if x != nil {
		return x.PodID
	}
	return ""
}

func (x *Payload) GetGcsPodID() string {
	if x != nil {
		return x.GcsPodID
	}
	return ""
}

func (x *Payload) GetNetwork() *anypb.Any {
	if x != nil {
		return x.Network
	}
	return nil
}

func (x *Payload) GetContainers() []*anypb.Any {
	if x != nil {
		return x.Containers
	}
	return nil
}

var File_github_com_Microsoft_hcsshim_internal_controller_pod_save_payload_proto protoreflect.FileDescriptor

const file_github_com_Microsoft_hcsshim_internal_controller_pod_save_payload_proto_rawDesc = "" +
	"\n" +
	"Ggithub.com/Microsoft/hcsshim/internal/controller/pod/save/payload.proto\x12\x1ehcsshim.controller.pod.save.v1\x1a\x19google/protobuf/any.proto\"\xcb\x01\n" +
	"\aPayload\x12%\n" +
	"\x0eschema_version\x18\x01 \x01(\rR\rschemaVersion\x12\x15\n" +
	"\x06pod_id\x18\x02 \x01(\tR\x05podId\x12\x1c\n" +
	"\n" +
	"gcs_pod_id\x18\x03 \x01(\tR\bgcsPodId\x12.\n" +
	"\anetwork\x18\x04 \x01(\v2\x14.google.protobuf.AnyR\anetwork\x124\n" +
	"\n" +
	"containers\x18\x05 \x03(\v2\x14.google.protobuf.AnyR\n" +
	"containersB@Z>github.com/Microsoft/hcsshim/internal/controller/pod/save;saveb\x06proto3"

var (
	file_github_com_Microsoft_hcsshim_internal_controller_pod_save_payload_proto_rawDescOnce sync.Once
	file_github_com_Microsoft_hcsshim_internal_controller_pod_save_payload_proto_rawDescData []byte
)

func file_github_com_Microsoft_hcsshim_internal_controller_pod_save_payload_proto_rawDescGZIP() []byte {
	file_github_com_Microsoft_hcsshim_internal_controller_pod_save_payload_proto_rawDescOnce.Do(func() {
		file_github_com_Microsoft_hcsshim_internal_controller_pod_save_payload_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_github_com_Microsoft_hcsshim_internal_controller_pod_save_payload_proto_rawDesc), len(file_github_com_Microsoft_hcsshim_internal_controller_pod_save_payload_proto_rawDesc)))
	})
	return file_github_com_Microsoft_hcsshim_internal_controller_pod_save_payload_proto_rawDescData
}

var file_github_com_Microsoft_hcsshim_internal_controller_pod_save_payload_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_github_com_Microsoft_hcsshim_internal_controller_pod_save_payload_proto_goTypes = []any{
	(*Payload)(nil),   // 0: hcsshim.controller.pod.save.v1.Payload
	(*anypb.Any)(nil), // 1: google.protobuf.Any
}
var file_github_com_Microsoft_hcsshim_internal_controller_pod_save_payload_proto_depIdxs = []int32{
	1, // 0: hcsshim.controller.pod.save.v1.Payload.network:type_name -> google.protobuf.Any
	1, // 1: hcsshim.controller.pod.save.v1.Payload.containers:type_name -> google.protobuf.Any
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_github_com_Microsoft_hcsshim_internal_controller_pod_save_payload_proto_init() }
func file_github_com_Microsoft_hcsshim_internal_controller_pod_save_payload_proto_init() {
	if File_github_com_Microsoft_hcsshim_internal_controller_pod_save_payload_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_github_com_Microsoft_hcsshim_internal_controller_pod_save_payload_proto_rawDesc), len(file_github_com_Microsoft_hcsshim_internal_controller_pod_save_payload_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_github_com_Microsoft_hcsshim_internal_controller_pod_save_payload_proto_goTypes,
		DependencyIndexes: file_github_com_Microsoft_hcsshim_internal_controller_pod_save_payload_proto_depIdxs,
		MessageInfos:      file_github_com_Microsoft_hcsshim_internal_controller_pod_save_payload_proto_msgTypes,
	}.Build()
	File_github_com_Microsoft_hcsshim_internal_controller_pod_save_payload_proto = out.File
	file_github_com_Microsoft_hcsshim_internal_controller_pod_save_payload_proto_goTypes = nil
	file_github_com_Microsoft_hcsshim_internal_controller_pod_save_payload_proto_depIdxs = nil
}
