// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: github.com/Microsoft/hcsshim/internal/computeagent/computeagent.proto

package computeagent

import (
	context "context"
	fmt "fmt"
	github_com_containerd_ttrpc "github.com/containerd/ttrpc"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	reflect "reflect"
	strings "strings"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type AddNICRequest struct {
	NamespaceID          string   `protobuf:"bytes,1,opt,name=namespace_id,json=namespaceId,proto3" json:"namespace_id,omitempty"`
	NicID                string   `protobuf:"bytes,2,opt,name=nic_id,json=nicId,proto3" json:"nic_id,omitempty"`
	EndpointID           string   `protobuf:"bytes,3,opt,name=endpoint_id,json=endpointId,proto3" json:"endpoint_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddNICRequest) Reset()      { *m = AddNICRequest{} }
func (*AddNICRequest) ProtoMessage() {}
func (*AddNICRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f2f03dc308add4c, []int{0}
}
func (m *AddNICRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AddNICRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AddNICRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AddNICRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddNICRequest.Merge(m, src)
}
func (m *AddNICRequest) XXX_Size() int {
	return m.Size()
}
func (m *AddNICRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddNICRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddNICRequest proto.InternalMessageInfo

type AddNICResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddNICResponse) Reset()      { *m = AddNICResponse{} }
func (*AddNICResponse) ProtoMessage() {}
func (*AddNICResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f2f03dc308add4c, []int{1}
}
func (m *AddNICResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AddNICResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AddNICResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AddNICResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddNICResponse.Merge(m, src)
}
func (m *AddNICResponse) XXX_Size() int {
	return m.Size()
}
func (m *AddNICResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddNICResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddNICResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*AddNICRequest)(nil), "containerd.runhcs.v1.computeagent.AddNICRequest")
	proto.RegisterType((*AddNICResponse)(nil), "containerd.runhcs.v1.computeagent.AddNICResponse")
}

func init() {
	proto.RegisterFile("github.com/Microsoft/hcsshim/internal/computeagent/computeagent.proto", fileDescriptor_7f2f03dc308add4c)
}

var fileDescriptor_7f2f03dc308add4c = []byte{
	// 319 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0xd1, 0xbd, 0x4e, 0xc3, 0x30,
	0x10, 0x07, 0xf0, 0x18, 0xd4, 0x4a, 0x75, 0x4b, 0x41, 0x11, 0x03, 0xea, 0x90, 0x96, 0x4e, 0x4c,
	0x0e, 0x2d, 0x23, 0x03, 0xea, 0xd7, 0xe0, 0x81, 0x0e, 0x99, 0x80, 0x05, 0xa5, 0xb6, 0x49, 0x2c,
	0x11, 0x5f, 0x88, 0x1d, 0x56, 0x78, 0x0a, 0x9e, 0xa9, 0x23, 0x23, 0x53, 0x45, 0xfd, 0x24, 0x28,
	0x09, 0x45, 0xed, 0x84, 0xba, 0xf9, 0x4e, 0xbf, 0x93, 0xef, 0xaf, 0xc3, 0xb3, 0x48, 0x9a, 0x38,
	0x5f, 0x10, 0x06, 0x89, 0x7f, 0x2b, 0x59, 0x06, 0x1a, 0x9e, 0x8c, 0x1f, 0x33, 0xad, 0x63, 0x99,
	0xf8, 0x52, 0x19, 0x91, 0xa9, 0xf0, 0xd9, 0x67, 0x90, 0xa4, 0xb9, 0x11, 0x61, 0x24, 0x94, 0xd9,
	0x29, 0x48, 0x9a, 0x81, 0x01, 0xf7, 0x9c, 0x81, 0x32, 0xa1, 0x54, 0x22, 0xe3, 0x24, 0xcb, 0x55,
	0xcc, 0x34, 0x79, 0x1d, 0x90, 0x6d, 0xd8, 0x39, 0x8d, 0x20, 0x82, 0x52, 0xfb, 0xc5, 0xab, 0x1a,
	0xec, 0x7f, 0x20, 0x7c, 0x34, 0xe2, 0x7c, 0x4e, 0x27, 0x81, 0x78, 0xc9, 0x85, 0x36, 0xee, 0x10,
	0xb7, 0x54, 0x98, 0x08, 0x9d, 0x86, 0x4c, 0x3c, 0x4a, 0x7e, 0x86, 0x7a, 0xe8, 0xa2, 0x31, 0x3e,
	0xb6, 0xab, 0x6e, 0x73, 0xbe, 0xe9, 0xd3, 0x69, 0xd0, 0xfc, 0x43, 0x94, 0xbb, 0x3d, 0x5c, 0x57,
	0x92, 0x15, 0xfa, 0xa0, 0xd4, 0x0d, 0xbb, 0xea, 0xd6, 0xe6, 0x92, 0xd1, 0x69, 0x50, 0x53, 0x92,
	0x51, 0xee, 0xfa, 0xb8, 0x29, 0x14, 0x4f, 0x41, 0x2a, 0x53, 0xb0, 0xc3, 0x92, 0xb5, 0xed, 0xaa,
	0x8b, 0x67, 0xbf, 0x6d, 0x3a, 0x0d, 0xf0, 0x86, 0x50, 0xde, 0x3f, 0xc1, 0xed, 0xcd, 0x5e, 0x3a,
	0x05, 0xa5, 0xc5, 0xf0, 0x0d, 0xb7, 0x26, 0x55, 0xa0, 0x51, 0x11, 0xc8, 0x05, 0x5c, 0xaf, 0x84,
	0x7b, 0x49, 0xfe, 0x8d, 0x4f, 0x76, 0x42, 0x76, 0x06, 0x7b, 0x4c, 0x54, 0xdf, 0xf7, 0x9d, 0xf1,
	0xfd, 0x72, 0xed, 0x39, 0x5f, 0x6b, 0xcf, 0x79, 0xb7, 0x1e, 0x5a, 0x5a, 0x0f, 0x7d, 0x5a, 0x0f,
	0x7d, 0x5b, 0x0f, 0x3d, 0xdc, 0xec, 0x7f, 0xc5, 0xeb, 0xed, 0xe2, 0xce, 0x59, 0xd4, 0xcb, 0x7b,
	0x5c, 0xfd, 0x04, 0x00, 0x00, 0xff, 0xff, 0xb8, 0xa9, 0xf2, 0x18, 0x11, 0x02, 0x00, 0x00,
}

func (m *AddNICRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AddNICRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.NamespaceID) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintComputeagent(dAtA, i, uint64(len(m.NamespaceID)))
		i += copy(dAtA[i:], m.NamespaceID)
	}
	if len(m.NicID) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintComputeagent(dAtA, i, uint64(len(m.NicID)))
		i += copy(dAtA[i:], m.NicID)
	}
	if len(m.EndpointID) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintComputeagent(dAtA, i, uint64(len(m.EndpointID)))
		i += copy(dAtA[i:], m.EndpointID)
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *AddNICResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AddNICResponse) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func encodeVarintComputeagent(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *AddNICRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.NamespaceID)
	if l > 0 {
		n += 1 + l + sovComputeagent(uint64(l))
	}
	l = len(m.NicID)
	if l > 0 {
		n += 1 + l + sovComputeagent(uint64(l))
	}
	l = len(m.EndpointID)
	if l > 0 {
		n += 1 + l + sovComputeagent(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *AddNICResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovComputeagent(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozComputeagent(x uint64) (n int) {
	return sovComputeagent(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *AddNICRequest) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&AddNICRequest{`,
		`NamespaceID:` + fmt.Sprintf("%v", this.NamespaceID) + `,`,
		`NicID:` + fmt.Sprintf("%v", this.NicID) + `,`,
		`EndpointID:` + fmt.Sprintf("%v", this.EndpointID) + `,`,
		`XXX_unrecognized:` + fmt.Sprintf("%v", this.XXX_unrecognized) + `,`,
		`}`,
	}, "")
	return s
}
func (this *AddNICResponse) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&AddNICResponse{`,
		`XXX_unrecognized:` + fmt.Sprintf("%v", this.XXX_unrecognized) + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringComputeagent(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}

type ComputeAgentService interface {
	AddNIC(ctx context.Context, req *AddNICRequest) (*AddNICResponse, error)
}

func RegisterComputeAgentService(srv *github_com_containerd_ttrpc.Server, svc ComputeAgentService) {
	srv.Register("containerd.runhcs.v1.computeagent.ComputeAgent", map[string]github_com_containerd_ttrpc.Method{
		"AddNIC": func(ctx context.Context, unmarshal func(interface{}) error) (interface{}, error) {
			var req AddNICRequest
			if err := unmarshal(&req); err != nil {
				return nil, err
			}
			return svc.AddNIC(ctx, &req)
		},
	})
}

type computeAgentClient struct {
	client *github_com_containerd_ttrpc.Client
}

func NewComputeAgentClient(client *github_com_containerd_ttrpc.Client) ComputeAgentService {
	return &computeAgentClient{
		client: client,
	}
}

func (c *computeAgentClient) AddNIC(ctx context.Context, req *AddNICRequest) (*AddNICResponse, error) {
	var resp AddNICResponse
	if err := c.client.Call(ctx, "containerd.runhcs.v1.computeagent.ComputeAgent", "AddNIC", req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}
func (m *AddNICRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowComputeagent
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AddNICRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AddNICRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NamespaceID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowComputeagent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthComputeagent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthComputeagent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NamespaceID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NicID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowComputeagent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthComputeagent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthComputeagent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NicID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EndpointID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowComputeagent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthComputeagent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthComputeagent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EndpointID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipComputeagent(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthComputeagent
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthComputeagent
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *AddNICResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowComputeagent
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AddNICResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AddNICResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipComputeagent(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthComputeagent
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthComputeagent
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipComputeagent(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowComputeagent
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowComputeagent
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowComputeagent
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthComputeagent
			}
			iNdEx += length
			if iNdEx < 0 {
				return 0, ErrInvalidLengthComputeagent
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowComputeagent
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipComputeagent(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
				if iNdEx < 0 {
					return 0, ErrInvalidLengthComputeagent
				}
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthComputeagent = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowComputeagent   = fmt.Errorf("proto: integer overflow")
)
