// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.26.0
// source: github.com/Microsoft/hcsshim/pkg/migration/migration.proto

package migration

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// FinalizeAction specifies the action to take on the sandbox during
// finalization. The concrete meaning depends on whether the call is made
// on the source or the destination — see the FinalizeSandbox RPC docs.
type FinalizeAction int32

const (
	// No action specified. Servers should treat this as an error.
	FinalizeAction_FINALIZE_ACTION_UNSPECIFIED FinalizeAction = 0
	// Stop and clean up the sandbox on this side. On the source this is
	// used after a successful migration; on the destination this is used
	// when the migration was cancelled or failed.
	FinalizeAction_FINALIZE_ACTION_STOP FinalizeAction = 1
	// Resume the sandbox on this side. On the destination this completes
	// a successful migration by bringing the migrated VM back to a
	// running state; on the source this is used to roll back when the
	// migration was cancelled or failed.
	FinalizeAction_FINALIZE_ACTION_RESUME FinalizeAction = 2
)

// Enum value maps for FinalizeAction.
var (
	FinalizeAction_name = map[int32]string{
		0: "FINALIZE_ACTION_UNSPECIFIED",
		1: "FINALIZE_ACTION_STOP",
		2: "FINALIZE_ACTION_RESUME",
	}
	FinalizeAction_value = map[string]int32{
		"FINALIZE_ACTION_UNSPECIFIED": 0,
		"FINALIZE_ACTION_STOP":        1,
		"FINALIZE_ACTION_RESUME":      2,
	}
)

func (x FinalizeAction) Enum() *FinalizeAction {
	p := new(FinalizeAction)
	*p = x
	return p
}

func (x FinalizeAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FinalizeAction) Descriptor() protoreflect.EnumDescriptor {
	return file_github_com_Microsoft_hcsshim_pkg_migration_migration_proto_enumTypes[0].Descriptor()
}

func (FinalizeAction) Type() protoreflect.EnumType {
	return &file_github_com_Microsoft_hcsshim_pkg_migration_migration_proto_enumTypes[0]
}

func (x FinalizeAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FinalizeAction.Descriptor instead.
func (FinalizeAction) EnumDescriptor() ([]byte, []int) {
	return file_github_com_Microsoft_hcsshim_pkg_migration_migration_proto_rawDescGZIP(), []int{0}
}

type PrepareAndExportSandboxRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identifier for the migration session. The same session_id is used on
	// both source and destination for the lifetime of this LM and is what
	// ties subsequent calls (TransferSandbox, FinalizeSandbox, etc.) back
	// to this sandbox.
	SessionID string `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// Source-side options that control how live migration is initialized
	// on the compute system.
	InitOptions   *MigrationInitializeOptions `protobuf:"bytes,2,opt,name=init_options,json=initOptions,proto3" json:"init_options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrepareAndExportSandboxRequest) Reset() {
	*x = PrepareAndExportSandboxRequest{}
	mi := &file_github_com_Microsoft_hcsshim_pkg_migration_migration_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareAndExportSandboxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareAndExportSandboxRequest) ProtoMessage() {}

func (x *PrepareAndExportSandboxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_Microsoft_hcsshim_pkg_migration_migration_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareAndExportSandboxRequest.ProtoReflect.Descriptor instead.
func (*PrepareAndExportSandboxRequest) Descriptor() ([]byte, []int) {
	return file_github_com_Microsoft_hcsshim_pkg_migration_migration_proto_rawDescGZIP(), []int{0}
}

func (x *PrepareAndExportSandboxRequest) GetSessionID() string {
	if x != nil {
		return x.SessionID
	}
	return ""
}

func (x *PrepareAndExportSandboxRequest) GetInitOptions() *MigrationInitializeOptions {
	if x != nil {
		return x.InitOptions
	}
	return nil
}

type PrepareAndExportSandboxResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Opaque, serialized snapshot of the source shim's view of the sandbox
	// and its containers. The caller must forward this verbatim as the
	// `config` field of ImportSandboxRequest on the destination; only the
	// destination shim knows how to decode it.
	Config        *anypb.Any `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrepareAndExportSandboxResponse) Reset() {
	*x = PrepareAndExportSandboxResponse{}
	mi := &file_github_com_Microsoft_hcsshim_pkg_migration_migration_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareAndExportSandboxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareAndExportSandboxResponse) ProtoMessage() {}

func (x *PrepareAndExportSandboxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_Microsoft_hcsshim_pkg_migration_migration_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareAndExportSandboxResponse.ProtoReflect.Descriptor instead.
func (*PrepareAndExportSandboxResponse) Descriptor() ([]byte, []int) {
	return file_github_com_Microsoft_hcsshim_pkg_migration_migration_proto_rawDescGZIP(), []int{1}
}

func (x *PrepareAndExportSandboxResponse) GetConfig() *anypb.Any {
	if x != nil {
		return x.Config
	}
	return nil
}

type ImportSandboxRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identifier for the migration session. Must match the session_id used
	// on the source for this LM.
	SessionID string `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// Opaque config produced by PrepareAndExportSandbox on the source.
	// Forwarded verbatim by the caller; the destination shim is responsible
	// for decoding and applying it.
	Config        *anypb.Any `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportSandboxRequest) Reset() {
	*x = ImportSandboxRequest{}
	mi := &file_github_com_Microsoft_hcsshim_pkg_migration_migration_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportSandboxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportSandboxRequest) ProtoMessage() {}

func (x *ImportSandboxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_Microsoft_hcsshim_pkg_migration_migration_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportSandboxRequest.ProtoReflect.Descriptor instead.
func (*ImportSandboxRequest) Descriptor() ([]byte, []int) {
	return file_github_com_Microsoft_hcsshim_pkg_migration_migration_proto_rawDescGZIP(), []int{2}
}

func (x *ImportSandboxRequest) GetSessionID() string {
	if x != nil {
		return x.SessionID
	}
	return ""
}

func (x *ImportSandboxRequest) GetConfig() *anypb.Any {
	if x != nil {
		return x.Config
	}
	return nil
}

type ImportSandboxResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportSandboxResponse) Reset() {
	*x = ImportSandboxResponse{}
	mi := &file_github_com_Microsoft_hcsshim_pkg_migration_migration_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportSandboxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportSandboxResponse) ProtoMessage() {}

func (x *ImportSandboxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_Microsoft_hcsshim_pkg_migration_migration_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportSandboxResponse.ProtoReflect.Descriptor instead.
func (*ImportSandboxResponse) Descriptor() ([]byte, []int) {
	return file_github_com_Microsoft_hcsshim_pkg_migration_migration_proto_rawDescGZIP(), []int{3}
}

type PrepareSandboxRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identifier for the migration session. Must match the session_id used
	// by ImportSandbox on this destination.
	SessionID string `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// Destination-side options that control how live migration is
	// initialized when the HCS compute system is created.
	InitOptions   *MigrationInitializeOptions `protobuf:"bytes,2,opt,name=init_options,json=initOptions,proto3" json:"init_options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrepareSandboxRequest) Reset() {
	*x = PrepareSandboxRequest{}
	mi := &file_github_com_Microsoft_hcsshim_pkg_migration_migration_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareSandboxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareSandboxRequest) ProtoMessage() {}

func (x *PrepareSandboxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_Microsoft_hcsshim_pkg_migration_migration_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareSandboxRequest.ProtoReflect.Descriptor instead.
func (*PrepareSandboxRequest) Descriptor() ([]byte, []int) {
	return file_github_com_Microsoft_hcsshim_pkg_migration_migration_proto_rawDescGZIP(), []int{4}
}

func (x *PrepareSandboxRequest) GetSessionID() string {
	if x != nil {
		return x.SessionID
	}
	return ""
}

func (x *PrepareSandboxRequest) GetInitOptions() *MigrationInitializeOptions {
	if x != nil {
		return x.InitOptions
	}
	return nil
}

type PrepareSandboxResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrepareSandboxResponse) Reset() {
	*x = PrepareSandboxResponse{}
	mi := &file_github_com_Microsoft_hcsshim_pkg_migration_migration_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareSandboxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareSandboxResponse) ProtoMessage() {}

func (x *PrepareSandboxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_Microsoft_hcsshim_pkg_migration_migration_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareSandboxResponse.ProtoReflect.Descriptor instead.
func (*PrepareSandboxResponse) Descriptor() ([]byte, []int) {
	return file_github_com_Microsoft_hcsshim_pkg_migration_migration_proto_rawDescGZIP(), []int{5}
}

type TransferSandboxRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identifier for the migration session. Must match the session_id used
	// for the rest of this LM on this side.
	SessionID string `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// Maximum time to wait for the migration socket / underlying transport
	// to become ready before the server gives up and reports a TIMEOUT
	// event on the response stream. If unset, the server applies a sensible
	// default (e.g. 10 minutes).
	Timeout       *durationpb.Duration `protobuf:"bytes,2,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferSandboxRequest) Reset() {
	*x = TransferSandboxRequest{}
	mi := &file_github_com_Microsoft_hcsshim_pkg_migration_migration_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferSandboxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferSandboxRequest) ProtoMessage() {}

func (x *TransferSandboxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_Microsoft_hcsshim_pkg_migration_migration_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferSandboxRequest.ProtoReflect.Descriptor instead.
func (*TransferSandboxRequest) Descriptor() ([]byte, []int) {
	return file_github_com_Microsoft_hcsshim_pkg_migration_migration_proto_rawDescGZIP(), []int{6}
}

func (x *TransferSandboxRequest) GetSessionID() string {
	if x != nil {
		return x.SessionID
	}
	return ""
}

func (x *TransferSandboxRequest) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

type TransferSandboxResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Monotonically increasing per-message counter on this stream. Useful
	// for de-duplication if the client reconnects mid-transfer.
	MessageID uint32 `protobuf:"varint,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	// Event-specific message describing the current migration notification.
	Event string `protobuf:"bytes,2,opt,name=event,proto3" json:"event,omitempty"`
	// Populated when `event` indicates an error or a timeout; empty
	// otherwise.
	Error string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	// Server-side timestamp of when the transfer began.
	StartTime *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	// Server-side timestamp of when this particular update was produced.
	UpdateTime    *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferSandboxResponse) Reset() {
	*x = TransferSandboxResponse{}
	mi := &file_github_com_Microsoft_hcsshim_pkg_migration_migration_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferSandboxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferSandboxResponse) ProtoMessage() {}

func (x *TransferSandboxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_Microsoft_hcsshim_pkg_migration_migration_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferSandboxResponse.ProtoReflect.Descriptor instead.
func (*TransferSandboxResponse) Descriptor() ([]byte, []int) {
	return file_github_com_Microsoft_hcsshim_pkg_migration_migration_proto_rawDescGZIP(), []int{7}
}

func (x *TransferSandboxResponse) GetMessageID() uint32 {
	if x != nil {
		return x.MessageID
	}
	return 0
}

func (x *TransferSandboxResponse) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

func (x *TransferSandboxResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *TransferSandboxResponse) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *TransferSandboxResponse) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

type FinalizeSandboxRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identifier for the migration session. Must match the session_id used
	// for the rest of this LM on this side.
	SessionID string `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// Action the shim should take on the sandbox during finalization. See
	// FinalizeAction and the FinalizeSandbox RPC documentation for the
	// per-side semantics of STOP vs. RESUME.
	Action        FinalizeAction `protobuf:"varint,2,opt,name=action,proto3,enum=FinalizeAction" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinalizeSandboxRequest) Reset() {
	*x = FinalizeSandboxRequest{}
	mi := &file_github_com_Microsoft_hcsshim_pkg_migration_migration_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinalizeSandboxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinalizeSandboxRequest) ProtoMessage() {}

func (x *FinalizeSandboxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_Microsoft_hcsshim_pkg_migration_migration_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinalizeSandboxRequest.ProtoReflect.Descriptor instead.
func (*FinalizeSandboxRequest) Descriptor() ([]byte, []int) {
	return file_github_com_Microsoft_hcsshim_pkg_migration_migration_proto_rawDescGZIP(), []int{8}
}

func (x *FinalizeSandboxRequest) GetSessionID() string {
	if x != nil {
		return x.SessionID
	}
	return ""
}

func (x *FinalizeSandboxRequest) GetAction() FinalizeAction {
	if x != nil {
		return x.Action
	}
	return FinalizeAction_FINALIZE_ACTION_UNSPECIFIED
}

type FinalizeSandboxResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinalizeSandboxResponse) Reset() {
	*x = FinalizeSandboxResponse{}
	mi := &file_github_com_Microsoft_hcsshim_pkg_migration_migration_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinalizeSandboxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinalizeSandboxResponse) ProtoMessage() {}

func (x *FinalizeSandboxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_Microsoft_hcsshim_pkg_migration_migration_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinalizeSandboxResponse.ProtoReflect.Descriptor instead.
func (*FinalizeSandboxResponse) Descriptor() ([]byte, []int) {
	return file_github_com_Microsoft_hcsshim_pkg_migration_migration_proto_rawDescGZIP(), []int{9}
}

type CreateDuplicateSocketRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identifier for the active LM session. Must match the session_id used
	// for the rest of this LM on this side.
	SessionID string `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// Serialized WSAProtocolInfo struct describing the source socket whose
	// handle should be duplicated into the shim process. The exact layout
	// is opaque to clients; the shim feeds it directly to WSASocket to
	// create the duplicate.
	ProtocolInfo  []byte `protobuf:"bytes,2,opt,name=protocol_info,json=protocolInfo,proto3" json:"protocol_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDuplicateSocketRequest) Reset() {
	*x = CreateDuplicateSocketRequest{}
	mi := &file_github_com_Microsoft_hcsshim_pkg_migration_migration_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDuplicateSocketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDuplicateSocketRequest) ProtoMessage() {}

func (x *CreateDuplicateSocketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_Microsoft_hcsshim_pkg_migration_migration_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDuplicateSocketRequest.ProtoReflect.Descriptor instead.
func (*CreateDuplicateSocketRequest) Descriptor() ([]byte, []int) {
	return file_github_com_Microsoft_hcsshim_pkg_migration_migration_proto_rawDescGZIP(), []int{10}
}

func (x *CreateDuplicateSocketRequest) GetSessionID() string {
	if x != nil {
		return x.SessionID
	}
	return ""
}

func (x *CreateDuplicateSocketRequest) GetProtocolInfo() []byte {
	if x != nil {
		return x.ProtocolInfo
	}
	return nil
}

type CreateDuplicateSocketResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDuplicateSocketResponse) Reset() {
	*x = CreateDuplicateSocketResponse{}
	mi := &file_github_com_Microsoft_hcsshim_pkg_migration_migration_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDuplicateSocketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDuplicateSocketResponse) ProtoMessage() {}

func (x *CreateDuplicateSocketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_Microsoft_hcsshim_pkg_migration_migration_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDuplicateSocketResponse.ProtoReflect.Descriptor instead.
func (*CreateDuplicateSocketResponse) Descriptor() ([]byte, []int) {
	return file_github_com_Microsoft_hcsshim_pkg_migration_migration_proto_rawDescGZIP(), []int{11}
}

var File_github_com_Microsoft_hcsshim_pkg_migration_migration_proto protoreflect.FileDescriptor

const file_github_com_Microsoft_hcsshim_pkg_migration_migration_proto_rawDesc = "" +
	"\n" +
	":github.com/Microsoft/hcsshim/pkg/migration/migration.proto\x1a\x19google/protobuf/any.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1aBgithub.com/Microsoft/hcsshim/pkg/migration/migration_options.proto\"\x7f\n" +
	"\x1ePrepareAndExportSandboxRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12>\n" +
	"\finit_options\x18\x02 \x01(\v2\x1b.MigrationInitializeOptionsR\vinitOptions\"O\n" +
	"\x1fPrepareAndExportSandboxResponse\x12,\n" +
	"\x06config\x18\x01 \x01(\v2\x14.google.protobuf.AnyR\x06config\"c\n" +
	"\x14ImportSandboxRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12,\n" +
	"\x06config\x18\x02 \x01(\v2\x14.google.protobuf.AnyR\x06config\"\x17\n" +
	"\x15ImportSandboxResponse\"v\n" +
	"\x15PrepareSandboxRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12>\n" +
	"\finit_options\x18\x02 \x01(\v2\x1b.MigrationInitializeOptionsR\vinitOptions\"\x18\n" +
	"\x16PrepareSandboxResponse\"l\n" +
	"\x16TransferSandboxRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x123\n" +
	"\atimeout\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\atimeout\"\xdc\x01\n" +
	"\x17TransferSandboxResponse\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\rR\tmessageId\x12\x14\n" +
	"\x05event\x18\x02 \x01(\tR\x05event\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x129\n" +
	"\n" +
	"start_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x12;\n" +
	"\vupdate_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"updateTime\"`\n" +
	"\x16FinalizeSandboxRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12'\n" +
	"\x06action\x18\x02 \x01(\x0e2\x0f.FinalizeActionR\x06action\"\x19\n" +
	"\x17FinalizeSandboxResponse\"b\n" +
	"\x1cCreateDuplicateSocketRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12#\n" +
	"\rprotocol_info\x18\x02 \x01(\fR\fprotocolInfo\"\x1f\n" +
	"\x1dCreateDuplicateSocketResponse*g\n" +
	"\x0eFinalizeAction\x12\x1f\n" +
	"\x1bFINALIZE_ACTION_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14FINALIZE_ACTION_STOP\x10\x01\x12\x1a\n" +
	"\x16FINALIZE_ACTION_RESUME\x10\x022\xd2\x03\n" +
	"\tMigration\x12\\\n" +
	"\x17PrepareAndExportSandbox\x12\x1f.PrepareAndExportSandboxRequest\x1a .PrepareAndExportSandboxResponse\x12>\n" +
	"\rImportSandbox\x12\x15.ImportSandboxRequest\x1a\x16.ImportSandboxResponse\x12A\n" +
	"\x0ePrepareSandbox\x12\x16.PrepareSandboxRequest\x1a\x17.PrepareSandboxResponse\x12F\n" +
	"\x0fTransferSandbox\x12\x17.TransferSandboxRequest\x1a\x18.TransferSandboxResponse0\x01\x12D\n" +
	"\x0fFinalizeSandbox\x12\x17.FinalizeSandboxRequest\x1a\x18.FinalizeSandboxResponse\x12V\n" +
	"\x15CreateDuplicateSocket\x12\x1d.CreateDuplicateSocketRequest\x1a\x1e.CreateDuplicateSocketResponseB6Z4github.com/Microsoft/hcsshim/pkg/migration;migrationb\x06proto3"

var (
	file_github_com_Microsoft_hcsshim_pkg_migration_migration_proto_rawDescOnce sync.Once
	file_github_com_Microsoft_hcsshim_pkg_migration_migration_proto_rawDescData []byte
)

func file_github_com_Microsoft_hcsshim_pkg_migration_migration_proto_rawDescGZIP() []byte {
	file_github_com_Microsoft_hcsshim_pkg_migration_migration_proto_rawDescOnce.Do(func() {
		file_github_com_Microsoft_hcsshim_pkg_migration_migration_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_github_com_Microsoft_hcsshim_pkg_migration_migration_proto_rawDesc), len(file_github_com_Microsoft_hcsshim_pkg_migration_migration_proto_rawDesc)))
	})
	return file_github_com_Microsoft_hcsshim_pkg_migration_migration_proto_rawDescData
}

var file_github_com_Microsoft_hcsshim_pkg_migration_migration_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_github_com_Microsoft_hcsshim_pkg_migration_migration_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_github_com_Microsoft_hcsshim_pkg_migration_migration_proto_goTypes = []any{
	(FinalizeAction)(0),                     // 0: FinalizeAction
	(*PrepareAndExportSandboxRequest)(nil),  // 1: PrepareAndExportSandboxRequest
	(*PrepareAndExportSandboxResponse)(nil), // 2: PrepareAndExportSandboxResponse
	(*ImportSandboxRequest)(nil),            // 3: ImportSandboxRequest
	(*ImportSandboxResponse)(nil),           // 4: ImportSandboxResponse
	(*PrepareSandboxRequest)(nil),           // 5: PrepareSandboxRequest
	(*PrepareSandboxResponse)(nil),          // 6: PrepareSandboxResponse
	(*TransferSandboxRequest)(nil),          // 7: TransferSandboxRequest
	(*TransferSandboxResponse)(nil),         // 8: TransferSandboxResponse
	(*FinalizeSandboxRequest)(nil),          // 9: FinalizeSandboxRequest
	(*FinalizeSandboxResponse)(nil),         // 10: FinalizeSandboxResponse
	(*CreateDuplicateSocketRequest)(nil),    // 11: CreateDuplicateSocketRequest
	(*CreateDuplicateSocketResponse)(nil),   // 12: CreateDuplicateSocketResponse
	(*MigrationInitializeOptions)(nil),      // 13: MigrationInitializeOptions
	(*anypb.Any)(nil),                       // 14: google.protobuf.Any
	(*durationpb.Duration)(nil),             // 15: google.protobuf.Duration
	(*timestamppb.Timestamp)(nil),           // 16: google.protobuf.Timestamp
}
var file_github_com_Microsoft_hcsshim_pkg_migration_migration_proto_depIdxs = []int32{
	13, // 0: PrepareAndExportSandboxRequest.init_options:type_name -> MigrationInitializeOptions
	14, // 1: PrepareAndExportSandboxResponse.config:type_name -> google.protobuf.Any
	14, // 2: ImportSandboxRequest.config:type_name -> google.protobuf.Any
	13, // 3: PrepareSandboxRequest.init_options:type_name -> MigrationInitializeOptions
	15, // 4: TransferSandboxRequest.timeout:type_name -> google.protobuf.Duration
	16, // 5: TransferSandboxResponse.start_time:type_name -> google.protobuf.Timestamp
	16, // 6: TransferSandboxResponse.update_time:type_name -> google.protobuf.Timestamp
	0,  // 7: FinalizeSandboxRequest.action:type_name -> FinalizeAction
	1,  // 8: Migration.PrepareAndExportSandbox:input_type -> PrepareAndExportSandboxRequest
	3,  // 9: Migration.ImportSandbox:input_type -> ImportSandboxRequest
	5,  // 10: Migration.PrepareSandbox:input_type -> PrepareSandboxRequest
	7,  // 11: Migration.TransferSandbox:input_type -> TransferSandboxRequest
	9,  // 12: Migration.FinalizeSandbox:input_type -> FinalizeSandboxRequest
	11, // 13: Migration.CreateDuplicateSocket:input_type -> CreateDuplicateSocketRequest
	2,  // 14: Migration.PrepareAndExportSandbox:output_type -> PrepareAndExportSandboxResponse
	4,  // 15: Migration.ImportSandbox:output_type -> ImportSandboxResponse
	6,  // 16: Migration.PrepareSandbox:output_type -> PrepareSandboxResponse
	8,  // 17: Migration.TransferSandbox:output_type -> TransferSandboxResponse
	10, // 18: Migration.FinalizeSandbox:output_type -> FinalizeSandboxResponse
	12, // 19: Migration.CreateDuplicateSocket:output_type -> CreateDuplicateSocketResponse
	14, // [14:20] is the sub-list for method output_type
	8,  // [8:14] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_github_com_Microsoft_hcsshim_pkg_migration_migration_proto_init() }
func file_github_com_Microsoft_hcsshim_pkg_migration_migration_proto_init() {
	if File_github_com_Microsoft_hcsshim_pkg_migration_migration_proto != nil {
		return
	}
	file_github_com_Microsoft_hcsshim_pkg_migration_migration_options_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_github_com_Microsoft_hcsshim_pkg_migration_migration_proto_rawDesc), len(file_github_com_Microsoft_hcsshim_pkg_migration_migration_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_github_com_Microsoft_hcsshim_pkg_migration_migration_proto_goTypes,
		DependencyIndexes: file_github_com_Microsoft_hcsshim_pkg_migration_migration_proto_depIdxs,
		EnumInfos:         file_github_com_Microsoft_hcsshim_pkg_migration_migration_proto_enumTypes,
		MessageInfos:      file_github_com_Microsoft_hcsshim_pkg_migration_migration_proto_msgTypes,
	}.Build()
	File_github_com_Microsoft_hcsshim_pkg_migration_migration_proto = out.File
	file_github_com_Microsoft_hcsshim_pkg_migration_migration_proto_goTypes = nil
	file_github_com_Microsoft_hcsshim_pkg_migration_migration_proto_depIdxs = nil
}
